### ISSUE TITLE
The GUI crashing on startup

### ISSUE THREAD

**Issue by dedddd** [hawku/TabletDriver#10]
So, I've uninstalled my Wacom drivers. I've tried many things to see if it's fixed, like reinstalling and restarting my PC to see if it works, but nothing does. Idk if it matters but I'm using w7 and CTL-471 https://puu.sh/zGPHA/b088903394.png

**Comment by Shoko84** [comment]
I've heard that there are some problems about _drivers_ on W7. It may have some issues when loading drivers and then instant crash 🤔 

Maybe @hawku does have an idea about why ?

**Comment by dedddd** [comment]
Haven't tried 12, I'll have a look

**Comment by hawku** [comment]
@dedddd Upload the startuplog.txt from the drivers's folder to here.

**Comment by dedddd** [comment]
Since 12 seems to not work for me, I'm trying 11. Here's the text file https://puu.sh/zGU3U/c356a03a96.txt

**Comment by hawku** [comment]
@dedddd Please, try the latest version: http://hwk.fi/TabletDriver/TabletDriverV0.0.14.zip

**Comment by dedddd** [comment]
Well, it still seems to crash but here's the startuplog https://puu.sh/zI7Vr/33fd482c8d.txt

**Comment by hawku** [comment]
@dedddd Try the latest version. I've added more debug information to the startuplog.txt

**Comment by dedddd** [comment]
I dunno, it's still crashing. Guess I'll just stick to the Wacom drivers

**Comment by Banbeucmas** [comment]
@dedddd startuplog.txt is for debugging. So I think you should reopen the driver and privide the new startuplog
