### ISSUE TITLE
Smoothing permanently on in Windows 7

### ISSUE THREAD

**Issue by mosvannen** [hawku/TabletDriver#103]
I tried using the driver on both my Windows 10 laptop my Windows 7 desktop, but on Windows 7 the driver seems to always smooth out inputs. On Windows 10 it behaves as it should, like the official 6.3.9w5 driver (without prediction). 

I've checked the console and it says `Smoothing = off`, and turning the smoothing filter on via the checkbox also doesn't make it feel any different than having it off.

I've also tested this with my CTL-471, with the same behavior discrepancies on the different OSes.

![image](https://user-images.githubusercontent.com/38150244/38461828-1b3b196e-3a8f-11e8-97a6-7059c55f0648.png)

## Hardware/software information
Windows Version: Windows 7 x64

Tablet Driver version: 0.1.4

Tablet model: Wacom CTH-480/CTL-471

**Comment by mosvannen** [comment]
I'm using 0 ms latency, as I want it to be as responsive as possible. When I put the latency to 100ms it works as expected (makes the cursor extremely slow and smooth).

What I'm trying to say is that this:
![image](https://user-images.githubusercontent.com/38150244/38473366-f2349eb8-3b43-11e8-9079-11ae7dfee6a7.png)
leads to the cursor motion still feeling slightly smoothed out instead of "raw input".

**Comment by hawku** [comment]
@mosvannen Does that happen with the Wacom 6.3.9w5 drivers?
Did you disable the Windows Aero?

**Comment by mosvannen** [comment]
The Wacom 6.3.9w5 drivers make the cursor very responsive and "raw" feeling, but with the cost of prediction. The 0.1.4 tablet driver in comparison just feels much more sluggish on Windows 7 compared to Windows 10. In addition, the Wacom drivers behave and feel the exact same on both OSes. 

I also have tried using the Classic, Basic, and Aero themes to no avail (DWM on/off changes nothing).

**Comment by mosvannen** [comment]
I don't know if it's placebo but the Windows Ink mode seems to increase the smoothing, but Relative doesn't feel any different other than behaving as a mouse. Setting smoothing to 1ms@125Hz doesn't change anything really.

Sorry for not being able to describe the issue better, but I'm sure that there's a difference to how the driver works/feels on Windows 7 vs Windows 10 (somehow).

**Comment by mosvannen** [comment]
Okay, so I discovered that in order to achieve the "raw" feeling of the tablet you have to first install and then uninstall Wacom drivers. Installing this tablet driver on a fresh Windows installation leads to the cursor movement feeling weird, as I described.

If you can't fix this, then it would be nice if you put some sort of disclaimer on the readme.
