### ISSUE TITLE
The driver only works for me if the Wacom drivers are uninstalled

### ISSUE THREAD

**Issue by FeatsM** [hawku/TabletDriver#1033]
I tried using the "DisableWacomDrivers" and it did close everything of my Wacom tablet, but in the console of the TabletDriver it says:
![tabletnotfound](https://user-images.githubusercontent.com/81049551/111886039-9c628200-89cb-11eb-97a0-3c2d23089637.png)
this happens when the Wacom driver is installed (even when I used the "DisableWacomDrivers"). After uninstalling the Wacom drivers the TabletDriver does work by putting this in the config/tablet.cfg file:
![wacomsettings](https://user-images.githubusercontent.com/81049551/111886106-09761780-89cc-11eb-968c-829abc24a38c.png)
But I need to restart my PC every time I install/uninstall the Wacom driver and that's pretty annoying if I want to draw and then switch to osu. I saw other people having the same problem but for them the "DisableWacomDrivers" tool does work. I think it's only happening with the CTL-6100.
If anyone knows a (temporary) fix to this I would appreciate it!

## Hardware/software information
Windows Version: 
Windows 10 
Tablet Driver version: 
v0.2.3
Tablet model: 
Wacom Intuos CTL-6100

**Comment by adryzz** [comment]
use OpenTabletDriver and switch between configuration files

**Comment by FreeHK-Lunity** [comment]
#1024

**Comment by FeatsM** [comment]
OpenTabletDriver works for me thank you both :)
