### ISSUE TITLE
DLL missing and error

### ISSUE THREAD

**Issue by Jeffrey983** [hawku/TabletDriver#104]
Hey so I tried to install the file to work for my huion 420, using the guide you've written. After installing I get messages like msvcp140.dll and vcruntime140.dll are missing, so I downloaded them manually. After that I get this: http://puu.sh/zY2wF/878bfd1745.png
Any way I can solve this? Thanks.

## Hardware/software information
Windows Version: 8.1 64-bit

Tablet Driver version: 0.0.14

Tablet model: Huion 420

**Comment by hawku** [comment]
https://github.com/hawku/TabletDriver#installation
