### ISSUE TITLE
Support fot CTH-300

### ISSUE THREAD

**Issue by ksitos** [hawku/TabletDriver#105]
## Hardware/software information
Windows Version: Winows 10 x64

Tablet Driver version: 0.1.4

Tablet model: CTH-300

**Comment by hawku** [comment]
@ksitos Is the CTH-300 a tablet?

I only found a touch pad with that model number.

**Comment by ksitos** [comment]
Yes and it looks like this

https://ptpimg.me/y5h4sy.jpg

**Comment by ksitos** [comment]
Well. It does have a touchpad and also it works with the pen too (it's not a stylus). You can hover it too.

**Comment by hawku** [comment]
@ksitos Can you capture the CTH-300 USB data with USBlyzer or similar?
I will need the data from the Wacom service restart and some pen movement data after that.

I can't guarantee that I can add support for the CTH-300, but I will need that USB data to determine if it is even possible.

**Comment by ksitos** [comment]
I'm not really sure if that's the right data but there you go

https://puu.sh/zZA9E.html

**Comment by hawku** [comment]
@ksitos I didn't see any messages being sent to the tablet by the Wacom drivers.
Did you restart the Wacom service while the USB capture was running?

You could try running the `tools\disable_wacom_drivers.bat` and add this to the `config\tablet.cfg`:
```
# Wacom CTH-300
Tablet 0x056A 0x0319 0xFF0D 0x0001
Tablet 0x056A 0x0319 0x000D 0x0001
Name "Wacom CTH-300"
ReportId 0x03
ReportLength 8
DetectMask 0x20
MaxX 10690
MaxY 6680
MaxPressure 511
Width 106.90
Height 66.80
InitFeature 0x02 0x02
```
