### ISSUE TITLE
Cursor is fading movement when pen is stopped

### ISSUE THREAD

**Issue by IrtenaX** [hawku/TabletDriver#106]
## Hardware/software information
Windows Version: 10 64bit Home

Tablet Driver version: 0.14

Tablet model: huion h640p
[Untitled Project.zip](https://github.com/hawku/TabletDriver/files/1887202/Untitled.Project.zip)

**Comment by hawku** [comment]
@IrtenaX Does that happen with the official drivers?

**Comment by IrtenaX** [comment]
Yes

**Comment by hawku** [comment]
@IrtenaX It has to be a hardware issue if the tablet doesn't work correctly even with the Huion's official drivers.

**Comment by IrtenaX** [comment]
Can you do something with this because it's some smoothering code or should I write to the huion support?

**Comment by hawku** [comment]
Yes, you should send a message to Huion support.

Huion H640P and H430P does have the highest amount of hardware input smoothing of all tablets that I have tested.
I've contacted Huion about that, but haven't got any reply yet.

**Comment by IrtenaX** [comment]
Ok thank you for the interest
