### ISSUE TITLE
Everything but Relative mode works

### ISSUE THREAD

**Issue by Ikxi1** [hawku/TabletDriver#1061]
Hello,
I tried using the Hawku drivers so I could try playing FPS with a tablet again.
But the relative mode is just not detecting any pen inputs.
The other modes work fine.
I have no other graphics tablet drivers installed.
Restarting the driver and even the whole PC does not fix the issue.

## Hardware/software information
Windows Version: Windows 10 (latest update just yesterday)

Tablet Driver version: 0.2.3

Tablet model: Wacom CTL-490
![grafik](https://user-images.githubusercontent.com/69396495/115140109-f3449100-a035-11eb-97f1-7cbf029a63de.png)

**Comment by SnowLire** [comment]
#1024

**Comment by Ikxi1** [comment]
> 
> 
> #1024

Ok, thank you
