### ISSUE TITLE
Absolute mode not working at all

### ISSUE THREAD

**Issue by TheOnlyPhoenix** [hawku/TabletDriver#1077]
Whenever I enable Absolute mode, the tablet just doesn't register any movement. I have the XP-Pen driver installed. Could it be that the original driver is prioritised over this one? It also uses the Active Area of the XP-Pen driver over this one. What can I do to fix this? I tried the OpenTabletDriver, but it was buggy and didn't have some functions that this does.

## Hardware/software information
Windows Version: 19042.928

Tablet Driver version: 0.2.3

Tablet model: XP-Pen Star G640

**Comment by Ponymous** [comment]
this repo is dead, you wont find any people willing to fix your problem

**Comment by SnowLire** [comment]
#1024

**Comment by TheOnlyPhoenix** [comment]
> #1024

alr ty ig
