### ISSUE TITLE
XP-PEN G640S problem 

### ISSUE THREAD

**Issue by m0x1337** [hawku/TabletDriver#1079]
Hello, i need help guys. I used a tablet with a 90 degree setting, but in this driver I do not see how to make a 90 degree tablet, here only the default value is 180 degrees, it is very uncomfortable for me to use it at 180 degrees and I cannot play like that, can I adjust the tablet to 90 degrees in this driver?

**Comment by SnowLire** [comment]
#1024

**Comment by m0x1337** [comment]
thanks
