### ISSUE TITLE
BLACK SCREEN

### ISSUE THREAD

**Issue by Minamoto-kun** [hawku/TabletDriver#108]
## Hardware/software information
Windows Version: 
7 SP10
Tablet Driver version: 
0.14
Tablet model: XP PEN G430

[https://pp.userapi.com/c834300/v834300924/10c19c/syEzwdoRh_Y.jpg](url)
Driver always crashes for me. but 2 times it's start working, but black screen...

**Comment by hawku** [comment]
https://www.google.fi/search?q=Windows+7+WPF+black+screen

https://social.msdn.microsoft.com/Forums/vstudio/en-US/a97bdc17-0f6b-4f5f-ae6a-7bbc850cba60/net-applications-not-loading-properly-blank-screen-wpf-issue?forum=wpf
