### ISSUE TITLE
Any way to check how much smoothing does my mouse have?

### ISSUE THREAD

**Issue by TLI1233** [hawku/TabletDriver#109]
I hope this is the right place to post this, anywas, I have the tablet driver installed and in us, but it feels a bit too responsive for me and I don't really like it, is there any way to check how much smoothing does my mouse have in ms? Because my mouse feels perfect.

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: TabletDriver v0.1.3

Tablet model: CTL-490

**Comment by hawku** [comment]
I don't know. Try searching mouse latency test results from internet.
