### ISSUE TITLE
Tablet not found! Error

### ISSUE THREAD

**Issue by FlamesInTheSky** [hawku/TabletDriver#1092]
I open up the TabletDriverGUI and it stops driver. I check console, says tablet not found. Using a supported tablet, installed each multidriver along with the website's driver (and promptly uninstalled the multidrivers when the problem was not fixed). Any suggestions?

![image](https://user-images.githubusercontent.com/84554467/119077666-95df8f00-b9a9-11eb-9af5-e0158f9b2c24.png)

## Hardware/software information
Windows Version: 10

Tablet Driver version: XP-PENWin_1.6.4.210111(Official Driver) 

Tablet model: XP-PEN Star G640

**Comment by SnowLire** [comment]
#1087
