### ISSUE TITLE
Cursor stuck with raw input in upper left corner.

### ISSUE THREAD

**Issue by dodoxs** [hawku/TabletDriver#110]
With Wacom drivers everything is fine (after disabling windows ink in wacom properties).
But i can't move my cursor from the left upper corner with ur's drivers :c.
It seems like it would be supporting Windows Ink still.
I'd really love to try those drivers.
Thanks in advance.

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.14

Tablet model: Wacom CTL-471

**Comment by hawku** [comment]
Attach the startuplog.txt from the driver's folder to a GitHub comment.

**Comment by Kurumya** [comment]
Did you disable your wacom driver before using  ?

**Comment by Tehzerrr** [comment]
turn raw input off
