### ISSUE TITLE
hello I need help with the deinstallation

### ISSUE THREAD

**Issue by lxstkrieger** [hawku/TabletDriver#1117]
when i click on remove_vmulti_driver to uninstall hawku it doesn't work. I then tried to put the files in the trash, but unfortunately that didn't work either
(sry for my english )

## Hardware/software information
Windows Version: 
Windows 10 Home
Tablet Driver version: 
0.2.3
Tablet model: 
wacoom-CTL-4100

**Comment by lxstkrieger** [comment]
I have another 2 problem. my cursor can't go further than the middle of the screen if that's fixed i don't need to uninstall the hawku driver either

**Comment by Mrcubix** [comment]
windows update broke hawku #1087

**Comment by lxstkrieger** [comment]
thank you for telling me i'm switched to the open tablet driver now, it feels a bit strange but i think that's normal when you change drivers 

(google translator) :)

**Comment by lxstkrieger** [comment]
but somehow i can't cope with the open tablet driver that is a different feeling than with the hawku driver it is normal
