### ISSUE TITLE
Driver found tablet but settings don't apply to the tablet

### ISSUE THREAD

**Issue by Desaje13** [hawku/TabletDriver#113]
## Hardware/software information
Windows Version: 10 64bit

Tablet Driver version: 0.1.4

Tablet model: Wacom CTL-472

**Comment by imNP** [comment]
@Desaje13 You'll need to provide some more information. Did you you hit the "Apply" and "Save" buttons after changing the settings you needed to? I know for certain settings unless you do that they won't take effect unless you do that or until you hit the "Restart Driver" button.

**Comment by Desaje13** [comment]
@imNP It tried to "Apply","Save","Restart" moreover I reinstalled driver about 4-5 times.  Problems appeared after 2 days of using.

**Comment by hawku** [comment]
@Desaje13 Does it say that "Wacom drivers installed" on the window title?
If it does then check the issue #1
