### ISSUE TITLE
Input problems!

### ISSUE THREAD

**Issue by Steds1330** [hawku/TabletDriver#114]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.4

Tablet model: XP-Pen G430
Hello, cursor starts moving only when I hold down the pen button or from a strong touch, what to do ? The problem arose after 1 day of game.

**Comment by hawku** [comment]
@Steds1330 Does that happen with the official drivers?

To me that looks like a hardware problem that driver can't fix.

**Comment by Steds1330** [comment]
No, it happened to your drivers.

**Comment by hawku** [comment]
@Steds1330 Uninstall the TabletDriver and test with the official drivers.

**Comment by Steds1330** [comment]
Um. strange, but after half a day it worked.
