### ISSUE TITLE
Define Tablet Area option

### ISSUE THREAD

**Issue by FinL73** [hawku/TabletDriver#115]
I think it would be cool to implement the same option that wacom has for their tablets to define your tablet area by tapping on the corners of the tablet you want to be your area (I have no idea why its so hard for me to explain, but I'm talking about this. https://puu.sh/A2c1g/1c26a22f13.png

## Hardware/software information
Windows Version: Windows 7 64 Bit

Tablet Driver version: 0.1.4

Tablet model: XP-PEN G640 #

**Comment by FinL73** [comment]
bump

**Comment by hawku** [comment]
@FinL73 This was implemented in the version 0.2.0
