### ISSUE TITLE
Hawku works on my pc but not my laptop

### ISSUE THREAD

**Issue by bl4ckh01e** [hawku/TabletDriver#1165]
## Hardware/software information
Windows Version: 10

Tablet Driver version: V0.2.3

Tablet model: Wacom CTL 472

I use Hawku on my pc just fine but on my laptop i get the error 'cant open vmulti device' despite doing the exact same thing on my pc.
for some reason my tablet worked on my laptop without me installing drivers and i have installed and uninstalled wacom drivers.

**Comment by SnowLire** [comment]
#1087
