### ISSUE TITLE
PTH-850 Drivers

### ISSUE THREAD

**Issue by mojobojo** [hawku/TabletDriver#117]
So with further testing of the config I added I found something that needs to be noted about the config I added for the PTH-850. Using this driver with the official Wacom drivers installed does not work. I tried 'disable_wacom_drivers.bat' but doesn't seem to work. Uninstalling the offical drivers and letting windows install their default driver for the tablet then using 'install_vmulti_driver.bat' seems to be the only way I got it running with the tablet. There could be a different VID or PID for the Wacom version that I need to look for.

**Comment by hawku** [comment]
@mojobojo the `disable_wacom_drivers.bat` is just an experimental feature, so it doesn't work with every tablet. That feature is only enabled on tablets that I can test before releasing a new version of the driver.

The PTH-850 support is already different from other Wacom tablets, so I don't know if it is possible to get that to work without uninstalling the Wacom drivers.
