### ISSUE TITLE
unable to change area on trust slimline tablet

### ISSUE THREAD

**Issue by athoni** [hawku/TabletDriver#119]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/1911647/startuplog.txt)

the gui recognizes it, but the area doesn't change, even though i changed it and saved

## Hardware/software information
Windows Version: 8.1 x64

Tablet Driver version: Windows 8.1 x64 (there's only one driver)

Tablet model:  Trust Slimline Widescreen
site :
https://www.trust.com/en/product/16529-slimline-widescreen-tablet

**Comment by hawku** [comment]
@athoni I don't think that it possible to use this driver with that tablet.
