### ISSUE TITLE
Driver stopped

### ISSUE THREAD

**Issue by 4ponks** [hawku/TabletDriver#1201]
## Hardware/software information
Windows Version: 10 

Tablet Driver version: newest

Tablet model: Xp-pen Star G640S
![Скриншот 13-12-2021 060140](https://user-images.githubusercontent.com/96033902/145746474-2527c155-2336-4b6f-b952-ae0674c9a91e.jpg)

**Comment by 4ponks** [comment]
Even after I reinstalled Windows, the drivers did not work

**Comment by jamesbt365** [comment]
#1087

**Comment by 4ponks** [comment]
@jamesbt365
Go fuck man, I don't give a shit about other drivers (I was able to fix the hawku problem) 

Upd: sorry, at that moment I got angry with that

**Comment by jamesbt365** [comment]
https://github.com/hawku/TabletDriver/blob/master/README.md <--
