### ISSUE TITLE
Tablet area is only half screen when using absolute mode with two screens

### ISSUE THREAD

**Issue by chicco-carone** [hawku/TabletDriver#1220]
If i use the open tablet driver the tablet area takes only half of the screen if i set to use only one screen of my two. If i use windows ink it takes all the screen

## Hardware/software information
Windows Version: Windows 10 pro 21h2

Tablet Driver version: 0.2.3

Tablet model: Wacom CTL-472

**Comment by jamesbt365** [comment]
read the readme
