### ISSUE TITLE
Opening then closing

### ISSUE THREAD

**Issue by LOwrYdr24** [hawku/TabletDriver#135]
No issues with driver ever, until the new windows update. Now, whenever I run the GUI, it appears in the task bar for a second then disappears, without ever showing up on screen. I have tried reinstalling drivers, running as admin, all compatibility settings, reinstalling then uninstalling old drivers, literally everything and no fix. I can't play the same with the normal drivers lol 

## Hardware/software information
Windows Version: Windows 10 1803

Tablet Driver version: 0.1.5

Tablet model: Huion 420

**Comment by hawku** [comment]
@LOwrYdr24 Try the latest version.
