### ISSUE TITLE
Driver uses both of my monitors 

### ISSUE THREAD

**Issue by AldumSK** [hawku/TabletDriver#136]
It worked all fine until one day, all of the sudden the driver used both of my monitors for my tablet area,I´ve set it as my main but that didn´t help . Only unplugging my second monitor helped. I´ve tried uninstalling and reinstalling it but it didn´t work, and I tried the older versions with no effect . pls help ;-;
(I also tried setting up the desktop size but it didnt change anything)

screenshoots: http://prntscr.com/je72nh
                      
## Hardware/software information
Windows Version: Win 10 Pro 64 Bit
                             10.0.16299 Build 16299

Tablet Driver version: I tried from ver0.1.2-0.1.5

Tablet model: CTL-471 (One by Wacom)

**Comment by AldumSK** [comment]
Ok now anther problem just occurred today, now it doesn´t use my tablet area at all it uses all of it...

**Comment by AldumSK** [comment]
Another update...
everthing works now after I just installed my original wacom driver and just closed the application, and tzhen running the GUI again. 
![hmm](https://user-images.githubusercontent.com/39014071/39671131-a134dc0a-5112-11e8-8931-535709e0a365.png)

**Comment by hawku** [comment]
@AldumSK Maybe Windows 10 automatically installed some Wacom drivers and installing the correct Wacom drivers fixed the problem.
