### ISSUE TITLE
switching between tablets

### ISSUE THREAD

**Issue by Felkiiee** [hawku/TabletDriver#139]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: 

If switching from a huion tablet to a wacom tablet would the 'install_huion_64.bat' have to be uninstalled for the wacom to work?

**Comment by hawku** [comment]
@Felkiiee You don't have to run the `remove_huion_64.bat` when switching tablets, but the official Huion drivers must be uninstalled when using this driver.
