### ISSUE TITLE
cth 680/s not found by the driver

### ISSUE THREAD

**Issue by Crazyrab1t98** [hawku/TabletDriver#14]
my cth 680/s is not found by the driver after following correctly (i think) all the path of the read me file

**Comment by Shoko84** [comment]
Just copying pasta from another issue :

> Add these lines to the Commands tab's first field and press Apply:
> 
> - log debug.txt
> - debug 1
> 
> That should create a debug.txt log file which contains lots of tablet status information.
> Try to reproduce the issue when the debug log is running.
> Log file will be huge if you play too long with logging enabled, but the log file will be cleared every time you apply or save settings.
> When you have captured the issue, close the GUI without saving or applying, zip the log file and upload it here.

Also, you should also write down on which OS you're running and which version of the TabletDriver you have (if it's not the latest one)
