### ISSUE TITLE
problem with my CTH-480 wacom

### ISSUE THREAD

**Issue by bassel707** [hawku/TabletDriver#140]
i do everything i unistall the wacom drivers i install vmulti and there is nothing called PentabletService.exe
in my Task Manager.
and it said "can't open VMulti device!" 
![screenshot_35](https://user-images.githubusercontent.com/39128233/39820084-a8e11d40-53ad-11e8-810b-99c3a17cdd97.png)

**Comment by Heli0saurus** [comment]
Same here with same tablet.

**Comment by Heli0saurus** [comment]
Never mind fixed it by uninstalling vmulti and reinstalling

**Comment by xyning** [comment]
try restarting ur computer(?)

**Comment by bassel707** [comment]
@Heli0saurus  are you using tabletdriver 0.1.5 ? or what

**Comment by bassel707** [comment]
it doesn't work for me :( i tried unistall vmulti and install it   and i restart my computer nothing work plz Help :((((

**Comment by bassel707** [comment]
i'm using TabletDriverV 0.1.5

**Comment by hawku** [comment]
@bassel707 What does it say when you try to install the VMulti driver?

You could try to unzip the TabletDriver to `C:\Temp\TabletDriver` directory and install the VMulti driver from there.

**Comment by bassel707** [comment]
![screenshot_37](https://user-images.githubusercontent.com/39128233/39886829-5468f8ea-5499-11e8-8f96-b5fbc015c31e.png)
and it doesn't do anything when i install Vmulti driver same probelm nothing happend and i tried to unzip the tablet driver to the Temp same problem :(((

**Comment by hawku** [comment]
@bassel707 It doesn't say anything when you press enter?

**Comment by bassel707** [comment]
@hawku  thank you it works now my pc was on windows 8.1   when i upgraded it to windows 10 it works for me. is this driver doesn't work on windows 8.1 or something ?
