### ISSUE TITLE
DLL's not found, tried everything

### ISSUE THREAD

**Issue by Tehzerrr** [hawku/TabletDriver#143]
VCruntime140.dll missing.
tried re installing visual studio, the msvcp110.dll isnt there either apparently. I moved my hard drives to my new pc from my old one, and it worked fine there. I re installed, re downloaded, did everything and nothing works. I cant play osu now because my pen is in touch mode when drivers arent on :/

## Hardware/software information
Windows Version: Windows 10 v1803 (i think)

Tablet Driver version: 0.1.5

Tablet model: cth 470

**Comment by hawku** [comment]
https://github.com/hawku/TabletDriver#installation
Check the step 1.
