### ISSUE TITLE
My cursor jumps on xp-pen g430

### ISSUE THREAD

**Issue by burakki916** [hawku/TabletDriver#144]
So for some reason once I installed the driver the cursors been jumping downwards for a split second. But as I move the cursor up the jump distance becomes smaller so at the very top of my screen there's barely any jumps. but at the bottom there's big jumps. 
Also this happens in and out of osu.
## Hardware/software information
Windows Version: 
Windows 8.1
Tablet Driver version: 
0.1.5
Tablet model: XP-pen g430

**Comment by hawku** [comment]
Does that happen with the official XP-Pen drivers?
To me that seems like a hardware problem.

**Comment by Zengo1k** [comment]
Hi , i have the same problem with my g403 not the s model , i have this problem only with the custom driver not with the xp pen driver

**Comment by hawku** [comment]
@burakki916 @Zengo1k Maybe you have XP-Pen drivers running in the background. Try the latest TabletDriver version.
