### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by davidew** [hawku/TabletDriver#146]
Windows 10 Home (1803)

v0.1.5

Wacom Intuos CTL 480

When starting TabletDriverService.exe I get a pop up sayin "System Error" followed by "The execution of the code could not continue because MSVCP140.dll. This problem can be solved reinstalling the program." And one that says the same except instead of MSVCP140.dll it's VCRUNTIME140.dll .

I've tried reinstalling and redownloading several times, but no changes.
I uninstalled my Wacom drivers.

**Comment by davidew** [comment]
Edit: I fixed it by installing vc_redist. Seems that was the solution.

**Comment by hhhhose** [comment]
what is vc_redist? im having the same issue but have no clue what the solution you listed is

**Comment by Banbeucmas** [comment]
@hhhhose
It is lised in the Readme.md of the software.
Just search it up. It is a kind of a library for the software to work.
