### ISSUE TITLE
Area problems

### ISSUE THREAD

**Issue by qweqweMar** [hawku/TabletDriver#147]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.15

Tablet model: Wacom pth 451

I used Wacom area and set my values and http://prntscr.com/jk156e http://prntscr.com/jk15bw this is not my area..

I just realised, after uninstalling Wacom drivers
and using vmulti to install the custom driver, my tablet stopped working, it's on but, the cursor ain't moving.

**Comment by hawku** [comment]
I think that you have the official Wacom drivers installed. Windows Check issue #1 for more information.
