### ISSUE TITLE
Cursor Jumps on XP-pen g430

### ISSUE THREAD

**Issue by Zengo1k** [hawku/TabletDriver#150]
Hi i have the same problem as burakki916 ,for some reason once I installed the driver the cursors been jumping downwards for a split second. But as I move the cursor up the jump distance becomes smaller so at the very top of my screen there's barely any jumps. but at the bottom there's big jumps.
Also this happens in and out of osu.

i have this problem only with the custom driver not with the xp pen driver

## Hardware/software information

Windows Version: 
Windows 10

Tablet Driver version: 
0.1.5

Tablet model:  XP-pen g430

**Comment by okicarde** [comment]
You had unistalled the xp drivers before install the hawku drivers?
