### ISSUE TITLE
Pen Pressure Tip

### ISSUE THREAD

**Issue by lucario386** [hawku/TabletDriver#152]
Is there a setting that mimics this function in wacom?

I love this driver for osu but I also use my tablet for drawing and I need to be able to play with this setting. 
![sj3qdni](https://user-images.githubusercontent.com/12094600/40424924-80f483ea-5ec9-11e8-9688-3fb250ba094b.jpg)

If it's not available right now, it is possible to implement it? Hope to hear from you very soon!

**Comment by hawku** [comment]
@lucario386 This was added in version 0.2.2
