### ISSUE TITLE
Tablet not being recognised, driver thinking it is a different unsupported tablet.

### ISSUE THREAD

**Issue by Inappreciation** [hawku/TabletDriver#153]
I uninstalled Wacom drivers, then installed your drivers and that was fine. Then I had a message saying the driver was being restarted so I checked Console. It says 'Tablet not found' but if I scroll up it detects a tablet model which is CTE-650 even though I have the CTL-490. How do I fix this?

## Hardware/software information
Windows Version:  10 

Tablet Driver version: Latest

Tablet model: CTL-490

**Comment by hawku** [comment]
Check #1
