### ISSUE TITLE
Buttons not working properly

### ISSUE THREAD

**Issue by Evill98** [hawku/TabletDriver#155]
The driver works perfectly fine otherwise but pen buttons and tapping the tablet with the pen are both broken. Buttons get randomly held down and they sometimes stop responding. Drawing with the tablet is impossible because it constantly holds down left click.

## Hardware/software information
Windows Version: Windows 10 Pro  1803

Tablet Driver version: 0.1.5

Tablet model: Wacom CTH-460

**Comment by Devocub** [comment]
Does this happen with official drivers?

**Comment by Evill98** [comment]
Apparently it also happens with official drivers. Something must be wrong with my pen in that case.
