### ISSUE TITLE
Huion H420 curor spazzing

### ISSUE THREAD

**Issue by FGVel0ciTy** [hawku/TabletDriver#156]
I started using this driver a couple weeks ago and it has worked amazingly. However, these past few days my cursor has been spazzing out when I press the bottom pen button while moving (I Have the pen side buttons disabled). While this doesn't happen every single time it still has messed up some good plays so I was wondering if it was a driver bug or just my tablet.

Thanks,
Vel0ciTy

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5

Tablet model: Huion H420

**Comment by Devocub** [comment]
Does this happen with the official Huron drivers?
