### ISSUE TITLE
Area 

### ISSUE THREAD

**Issue by VanillaOsq** [hawku/TabletDriver#157]
Can i change my Tablet Area in this driver ? Cause i dont get it how, i know only how to move the area in x and y direction. 
I uploadet my Wacom Area but now i want to change it. Do i have to get the other driver back and than come back to this driver only to change my area ?

**Comment by shibou3** [comment]
You can change using method (1 and 2) in this picture, you can't "draw" an area yet.
![tabletdrivergui_2018-06-01_00-43-10](https://user-images.githubusercontent.com/23579978/40820095-e906ccba-6534-11e8-8471-c026f264b98b.jpg)

**Comment by VanillaOsq** [comment]
Okay, thank you :)

**Comment by BYSTACK** [comment]
You should close the issue if the problem is solved
