### ISSUE TITLE
XP Pen G430S  Incompatibility

### ISSUE THREAD

**Issue by eightoe** [hawku/TabletDriver#164]
I have had the older version of the G430 and had recently switched to the newer version of G430S. When trying to use the community drivers I had seen that the tablet was only being detected on the left half of the play area and the driver was detecting it as XP Pen G430 not the newer version. Wondering if there was a fix for this bug or I might have to go back to the drivers from XP Pen. Thanks.

## Hardware/software information
Windows Version:  10

Tablet Driver version:  0.0.18

Tablet model: XP Pen G430S

**Comment by Devocub** [comment]
check #138

**Comment by hawku** [comment]
@eightoe Please, check the issue #301
