### ISSUE TITLE
tablet stops working if I click osu with mouse

### ISSUE THREAD

**Issue by Shinwoir** [hawku/TabletDriver#165]
If I click the osu icon with my mouse click(to get into osu) while it's already open, the tablets stop working until I change song with the keyboard. If I open osu! with the tablet though, it works all fine

## Hardware/software information
Windows Version:  7

Tablet Driver version: 0.1.5

Tablet model: Wacom CTH 480-S

**Comment by hawku** [comment]
@Shinwoir Are you sure that driver is not in Windows Ink mode?
