### ISSUE TITLE
issue w/ installing vmulti driver

### ISSUE THREAD

**Issue by ghost** [hawku/TabletDriver#167]
I have an issue with installing the vmulti driver 
![dev](https://user-images.githubusercontent.com/40132765/41198090-8c14328e-6c3e-11e8-95f3-64a005d0f386.png)
i tried to unzip the driver to a shorter path but it didn't work. 
![ye](https://user-images.githubusercontent.com/40132765/41198096-dc88c694-6c3e-11e8-9964-9edb65d2b7f7.png)
this is what happens when i try to run tabletdrivergui.exe
I have installed the drivers following the steps, and also tried to re download the libraries provided

## Hardware/software information
Windows Version: 7 ultimate 64 bit

Tablet Driver version: 0.1.5

Tablet model: ctl 480

**Comment by YChvanov** [comment]
You are not to copy-paste "install_vmulti_64.bat" script in cmd, you have to rmb it in explorer and select 'Run as administrator'

**Comment by yeezyseasom21** [comment]
I didn't copy paste the script in cmd, I just ran "install_vmulti_driver.bat" as administrator in the TabletDriverV0.0.15 folder and this is what I got: 
![yexd](https://user-images.githubusercontent.com/40132765/41207624-fd434258-6ce6-11e8-8992-d92e069c2c3f.png)
