### ISSUE TITLE
problem on dual screen

### ISSUE THREAD

**Issue by andyrkn** [hawku/TabletDriver#169]
## Hardware/software information
Windows Version:  win10

Tablet Driver version: latest

Tablet model: ctl 480 wacom

Laptop(gtx 950m at 768p) , got a 1080p plugged into the laptop on which i play, when trying to set the area on the second screen , it only registers half of it regardless of what i set. can only fix this by disabling the laptop screen trough windows, restarting the driver connecting the tablet and then turning on the screen again

**Comment by simo3003** [comment]
Please post a screenshot of your settings.

**Comment by andyrkn** [comment]
https://puu.sh/AECKR/a3860438d6.png

**Comment by Devocub** [comment]
You said you use latest version of driver but you doesn't

**Comment by andyrkn** [comment]
https://puu.sh/AED2I/0e9983c6c2.png

problem still persists

**Comment by hawku** [comment]
You could try to disable the automatic desktop size and set the desktop width and height to match the external monitor.

**Comment by andyrkn** [comment]
it doesnt work,

**Comment by hawku** [comment]
@andyrkn Problem might be with how Windows handles absolute mouse positioning. Some displays just can't be used with absolute mouse.
I can't replicate that problem, so there is no solution for that yet.

**Comment by andyrkn** [comment]
@hawku have you tested with two monitors off different resolution?
