### ISSUE TITLE
Very shaky

### ISSUE THREAD

**Issue by Rexzosu** [hawku/TabletDriver#177]
https://www.youtube.com/watch?v=Q44rPRGT10Y
^This is with hovering, stationary it still shakes but a little less.
I read that other people have a lot of shakyness, but I also see other streamers using custom driver and their cursor is as still as if they were using mouse. Is there any help/insight you can give?
Thanks for the amazing driver regardless <3 

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: CTH-480

**Comment by Devocub** [comment]
https://github.com/hawku/TabletDriver/wiki/FAQ#q-why-is-the-cursor-shaking
https://github.com/Devocub/TabletDriver

**Comment by Rexzosu** [comment]
Is that considered small amount?

**Comment by Rexzosu** [comment]
Tried your driver and it fixed the shaking, thank you so much <3
