### ISSUE TITLE
My cursor can't reach edge of the screen

### ISSUE THREAD

**Issue by PeraSite** [hawku/TabletDriver#179]
**I READ THE FAQ.**
I tried bunch of things like reinstall but all of them is not working.
Ofcourse i tried "Map absolute raw input to osu! window" setting but same.

Additionally, if i take off the pen from tablet my cursor goes to left top corner.
This happens in Windows but in osu, it goes to top left corner of "reachable area". 
![osu cursor](https://user-images.githubusercontent.com/19837403/41720665-b75f8718-759e-11e8-814a-7cd93e6dcfc1.png)

## Hardware/software information
Windows Version: Windows 10 Pro 17134.112

Tablet Driver version: 0.1.5

Tablet model: CTL-470

**Comment by hawku** [comment]
@PeraSite Try the latest version. Compatibility/SendInput mode might help with that.
