### ISSUE TITLE
Driver won't work on Wacom CTL-472

### ISSUE THREAD

**Issue by Akumaii** [hawku/TabletDriver#181]
The driver won't work with my tablet,i tried pretty much everything i could and it still doesn't work,i've uninstalled my other drivers,set my area,tried applying and saving many times,tried restarting the driver through the "Restart Driver" Button and tried closing the driver and opening it again

## Hardware/software information
Windows Version: 10 

Tablet Driver version: 0.1.5

Tablet model: Wacom CTL472

**Comment by Banbeucmas** [comment]
It worked perfectly fine for me?
Try running the driver in Admin mode?

**Comment by hawku** [comment]
Check #1
