### ISSUE TITLE
"ERROR! Can't start the driver!", "Access is denied"

### ISSUE THREAD

**Issue by iOppy** [hawku/TabletDriver#185]
As the title states I my TabletDriver does not work at all and displays that error in the console ever since I tried updating it from the original version that I have had. I have tried everything, uninstalling, reinstalling, restarts, etc. I would appreciate some assistance so that I can get my drawing tablet back up and running again!

Thanks,

~Oppy

**## Hardware/software information**

**Windows Version:** Windows 10

**Tablet Driver version:** TabletDriverV0.1.5

**Tablet model:** Wacom Intuos Pro PTH-451

**Comment by Banbeucmas** [comment]
May be open the TabletDriverGUI as Administrator works?

**Comment by iOppy** [comment]
@Banbeucmas The application is already to "Run As Administrator" by default after I manually went into properties and set it up that way... Since I too thought that was the problem before I came here, but that was not the case and still received the same error after multiple attempts.


~Oppy

**Comment by hawku** [comment]
@iOppy Where did you unzip the driver?
Try to unzip it to `C:\Temp\TabletDriver` directory
