### ISSUE TITLE
Driver not responding

### ISSUE THREAD

**Issue by Killbasa** [hawku/TabletDriver#186]
Been using these drivers for the past few months without issue, but as of recent as soon as I open the program it does not respond and lags my whole PC.

https://i.imgur.com/ReTZq15.png

I've tried to fix it to the best of my ability but nothing has worked. Not sure what's wrong.

## Hardware/software information
Windows Version: Windows 10 Pro

Tablet Driver version: 0.1.5

Tablet model: CTL-480

**Comment by hawku** [comment]
@Killbasa I don't how to fix that. I can't replicate the problem.
You could try the latest version.
