### ISSUE TITLE
Access is denied.

### ISSUE THREAD

**Issue by zappy1321** [hawku/TabletDriver#19]
On console it just says ERROR! Can't start driver. Access is denied." I uninstalled old wacom drivers. Reinstalling no good either.

**Comment by Shoko84** [comment]
Just copying pasta from another issue :

> Add these lines to the Commands tab's first field and press Apply:
> 
> - log debug.txt
> - debug 1
> 
> That should create a debug.txt log file which contains lots of tablet status information.
> Try to reproduce the issue when the debug log is running.
> Log file will be huge if you play too long with logging enabled, but the log file will be cleared every time you apply or save settings.
> When you have captured the issue, close the GUI without saving or applying, zip the log file and upload it here.

Also, which OS are you on ? Which TabletDriver's version are you using ? This can be helpful to help out and fix your issue
