### ISSUE TITLE
Area !!!!

### ISSUE THREAD

**Issue by SaaYio** [hawku/TabletDriver#191]
The area does not apply on my Tablet

I think it's due to the windows driver for wacom

software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: wacom CTL-471

**Comment by R-E-V** [comment]
Dude if your windows version is 1803 your going have to wait for a patch for the tablet ui

**Comment by hawku** [comment]
@SaaYio Windows 10 may have automatically installed drivers for your tablet. Check device manager.
