### ISSUE TITLE
Random jumps everytime i put the pen on tab

### ISSUE THREAD

**Issue by AngelDez** [hawku/TabletDriver#195]
Hello,
i am currently having this trouble of the cursor teleporting when i start to use the pen, like moving it up and down, im using relative mode.
I doubt its a machine issue, i have 2 working tablet, an H420[brand new] and a G430, both have the same issue using TabletDriver, i dont use TD on G430 because the original driver has relative mode, but H420 doesnt so i use TD, is there a fix to this? i havent seen a post having the same problem, if do, please link :(
Oh, and it works normally when using it, its just the random jumps when i put it back on the tablet is the one bugging me

here's how it looks, im moving it up and down
https://youtu.be/4gX1R4Dso94

## Hardware/software information
Windows Version:  Windows 10

Tablet Driver version:  0.1.5

Tablet model: Huion H420

**Comment by hawku** [comment]
@AngelDez You may have XP-Pen drivers running in the background.
Try the latest TabletDriver version. XP-Pen driver processes are now killed when the TabletDriverGUI starts.
