### ISSUE TITLE
How do I create my own config

### ISSUE THREAD

**Issue by Acclaiming** [hawku/TabletDriver#200]
I have a tablet that is not currently supported (Gaomon m106k)and would like to make a config but I do not understand how exactly the config works, a few answers would be appreciated:

How do I get the device/registry? id after tablet like this:

> Tablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}" 201 HUION_T156

How can I determine MaxX and MaxY?

How do I determine Width and Height? (I thought initially this was tablet area in mm but it diverged on the huion osu tablet)

If I do finish a working config I will of course provide it.

Thanks for your help in advance !

**Comment by hawku** [comment]
@Acclaiming Try the latest version.
It should detect the tablet as an unknown Huion tablet and will show more information about that tablet in the `startuplog.txt`.

MaxX and MaxY values you can get by enabling the debug checkbox in the console tab.
Width and height values should be the exact values of tablet area in millimeters.

Correct values might be: MaxX=50800, MaxY=31760. Width=254, Height=158.8
