### ISSUE TITLE
32 Bit Support To An Extent

### ISSUE THREAD

**Issue by githubnori** [hawku/TabletDriver#201]
For now I only know that this works with Huion H420 and Huion 420. Of course when on 32 Bit you can't download the VMulti driver but a way around this is to download the Huion supplied driver for the H420 and 420 and launch TabletDriverGUI without opening the Huion TabletDriver. 

## Hardware/software information
Windows Version: Windows 10 32 Bit

Tablet Driver version: v0.1.5

Tablet model: Huion 420

**Comment by hawku** [comment]
@githubnori Latest version does include 32-bit versions of VMulti and Huion drivers.
