### ISSUE TITLE
Still a lot of smoothing on Huion H640P

### ISSUE THREAD

**Issue by Fronsipswu** [hawku/TabletDriver#202]
Using your drivers with my CTL-490 is fast, responsive and free of input lag just like what everyone claims but however with my Huion H640P, although your drivers fixes the awkward cursor movement found in the original drivers, there are still a lot of smoothing (both hovering and drag) and the delay is quite noticeable even with smoothing filter disabled. I am able to achieve the least input delay on Huion H640P with the plug and play mode but the cursor positions are wrong with that. would be great if you have a look into this issue.

## Hardware/software information
Windows Version: Windows 8.1

Tablet Driver version: 0.1.5 [latest]
![image](https://user-images.githubusercontent.com/40987431/42436900-9f6cbe92-8385-11e8-9417-8576b38bfd59.png)

Tablet model: H640P

**Comment by hawku** [comment]
Huion H640P does the smoothing on the tablet hardware itself, so currently it can't be disabled or reduced.
I asked Huion about that smoothing problem three months ago and the response was: 

> Our technical team is making improvement on both the hardware and software for the tablets to optimize on them.
We will update to you is any there is any news.

&nbsp;
I haven't got any update yet...
