### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Reddddddddd** [hawku/TabletDriver#203]
![help me](https://user-images.githubusercontent.com/41098586/42549809-c01e3102-8493-11e8-995f-53d356fa7765.PNG)

## Hardware/software information
Windows Version: 10

Tablet Driver version: 1.5

Tablet model: xp-pen g430

**Comment by Banbeucmas** [comment]
Put the driver on another drive

**Comment by Reddddddddd** [comment]
now im getting this
![halp](https://user-images.githubusercontent.com/41098586/42554439-848aeb3c-84aa-11e8-964f-0c0fe1a3c779.PNG)

**Comment by Banbeucmas** [comment]
Reinstall C++ 2015
As said on the main page.

> 
You might need to install these libraries, but usually these are already installed:

https://www.microsoft.com/net/download/dotnet-framework-runtime
https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by Reddddddddd** [comment]
Thanks
