### ISSUE TITLE
Pen pressure

### ISSUE THREAD

**Issue by Kaktusboi** [hawku/TabletDriver#204]
Does the driver not have pen pressure detection? I figured it might be there if there is a smoothening filter. I can't find it or do I have to install the stock driver every time I want to draw again?

Thanks in advance for the help

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5

Tablet model: Wacom CTL 672

**Comment by BYSTACK** [comment]
#84

**Comment by Kaktusboi** [comment]
My bad, should've searched first
