### ISSUE TITLE
vmulti driver won't install

### ISSUE THREAD

**Issue by Astarthee** [hawku/TabletDriver#206]
## Hardware/software information
Windows Version: Windows 10 Enterprise N

Tablet Driver version:  every version

Tablet model: ctl 471

![2](https://user-images.githubusercontent.com/38910209/42734988-096b559e-884d-11e8-983f-8eaaffc2ecf9.png)

When i press enter to install driver, the window suddenly disappears. Is there any fix to that? Or another way to install the driver?

**Comment by YChvanov** [comment]
try to to run the .bat directly, it's in the driver_vmulti folder

**Comment by Astarthee** [comment]
It still disappears D:

**Comment by hawku** [comment]
@Astarthee Are you using 32-bit Windows 10?
