### ISSUE TITLE
Wacom CTH-690

### ISSUE THREAD

**Issue by jophes123** [hawku/TabletDriver#210]
Vmulti driver isn't even there when extracted. When I try to download it in the zip it doesn't even work and says this 
http://prntscr.com/k7kpoz . If I run the GUI it keeps saying in the bottom left http://prntscr.com/k7kqa9
and in the console it repeats http://prntscr.com/k7kqp7 the tablet is completely unresponsive.

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: CTH-690

**Comment by hawku** [comment]
@jophes123 Try to unzip the zip file to an another folder. VMulti driver is in the zip file.
