### ISSUE TITLE
Screen mapping doesn't work properly with multiple monitors on Win 8.1 

### ISSUE THREAD

**Issue by NightCourtdan** [hawku/TabletDriver#211]
The only fix I saw was to upgrade to windows 10.  Was there ever a work around found?  I had the old .10 version of the tablet driver and everything worked great, figured id update to the new driver and now its broken.  Not wanting to map to the whole screen just like in this: https://github.com/hawku/TabletDriver/issues/4

## Hardware/software information
Windows Version: 8.1

Tablet Driver version: http://hwk.fi/TabletDriver/TabletDriverV0.1.5.zip

Tablet model: ctl 480

**Comment by hawku** [comment]
Latest driver versions does have SendInput/Compatibility mode that might fix this problem.
