### ISSUE TITLE
MSVCP140.dll and VCRUNTIME140.dll are missing for the driver but are installed in System 32

### ISSUE THREAD

**Issue by Amano63729** [hawku/TabletDriver#214]
## Hardware/software information
Windows Version: 10

Tablet Driver version: Latest

Tablet model: H420

**Comment by YChvanov** [comment]
Have you tried to reinstall MSVC?

**Comment by Amano63729** [comment]
@YChvanov 

Yes i have and the issue still seemed to occur

**Comment by hawku** [comment]
@Amano63729 Did you install correct runtimes: https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by Boomy639** [comment]
thank you hawku, i just had the same issue installing anything and everything i could find
