### ISSUE TITLE
Active Area/Screen size does not change my sensitivity

### ISSUE THREAD

**Issue by Sttarkson** [hawku/TabletDriver#218]
As the title says, the driver simply does not work for me when it comes to changing the active area on my tablet, or maybe it bugs out, I'm not sure. If I set an area on the driver, click apply, save and minimize the window, then I go in-game and it's just... wrong. For instance, with the xp pen drivers if you set an active area and put your pen somewhere outside the active area, nothing would happen. With these drivers however, not only does changing the active area not descrease my sensitivity, but if I put my pen outside it on the tablet, my cursor teleports there on screen but it cannot move until I get back within my active area.

## Hardware/software information
Windows Version: https://gyazo.com/77c991f38a139e3ec9fc95d76fce7e94

Tablet Driver version: 0.1.5

Tablet model: XP Pen G640

**Comment by hawku** [comment]
@Sttarkson Try the latest version.
