### ISSUE TITLE
Area not updating

### ISSUE THREAD

**Issue by KaiMinCL** [hawku/TabletDriver#222]
I tried changing my tablet area but it's not updating and its freeze the cursor in the upper left corner of the osu client when raw input is enable. I have uninstalled the wacom drivers. 

I have used this drivers before on my old windows pc and it worked fine.

## Hardware/software information
Windows Version: Windows 10 64 bits version 1803

Tablet Driver version: 0.1.5

Tablet model: CTH-480

**Comment by hawku** [comment]
@KaiMinCL Windows 10 might have installed Wacom drivers automatically. Check device manager.
