### ISSUE TITLE
Pen Pressure Support?

### ISSUE THREAD

**Issue by Cliche45** [hawku/TabletDriver#223]
Since i bought this tablet to play osu! and to draw on, when will this driver have support for pen pressure? Because it would really be annoying to keep switching from this driver to the OEM driver.

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model:  XP-pen Star G430S

**Comment by YChvanov** [comment]
Driver do support it. Use "Windows Ink" mode instead of "Absolute (osu!)".

**Comment by BYSTACK** [comment]
#84, #95.
