### ISSUE TITLE
driver disables left click keybind

### ISSUE THREAD

**Issue by Naivesonic99** [hawku/TabletDriver#224]
So i just started using this driver bc everyone knows how crappy the xp pen driver is and now in osu my left click is bound to x. Whenever i click it out of an osu map it works. But  in an osu map when i click it, the game doesn't sense it. I can tell because i have ripples on when i click. Someone pls send help

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: 
xp-pen star g640

**Comment by hawku** [comment]
@Naivesonic99 There shouldn't be any ripples when you click.
Windows Ink mode might cause those ripples and it shouldn't be used with osu!
