### ISSUE TITLE
"devcon.exe failed" i get this issue, everytime i try to install my tablet drivers.

### ISSUE THREAD

**Issue by SgtCataclyst** [hawku/TabletDriver#225]
## Hardware/software information
Windows Version: 10

Tablet Driver version: V0.1.5

Tablet model: Wacom CTL 490DW-S

**Comment by hawku** [comment]
@SgtCataclyst Are you running 32-bit Windows 10?
The latest driver zip file will provide 32-bit version of VMulti driver.

**Comment by Miguel2004** [comment]
Please could you help me with this problem of "devcon.exe failed".
I am using a small size ctl-471, and my operating system is windows 8.1 64-bit.

**Comment by hawku** [comment]
@Miguel2004 I can't reproduce the problem, so it is very hard to help with that problem.
You could try to run `driver_vmulti\install_vmulti_64.bat` as an administrator.

**Comment by Miguel2004** [comment]
I tried to open as administrator but the program opens and when I press enter to download it closes without downloading the driver.

**Comment by hawku** [comment]
@Miguel2004 Maybe your anti-virus is blocking the devcon.exe?
Can you run the the devcon.exe in the command prompt?

**Comment by Miguel2004** [comment]
I tried and it does not work. My anti-virus is disabled too.

**Comment by hawku** [comment]
@Miguel2004 Try to unzip the driver to another folder. For example `C:\Temp\TabletDriver\`
If that doesn't help, you have to find a solution from google. For example:
https://social.msdn.microsoft.com/Forums/en-US/de483d5e-ffc9-41fd-b887-11cdfd874515/devcon-failed?forum=windowspro-audiodevelopment

**Comment by Miguel2004** [comment]
![driver erro](https://user-images.githubusercontent.com/46331609/50618523-85164780-0eda-11e9-94b5-c421fc92d257.PNG)
This is the driver installation error

**Comment by hawku** [comment]
@Miguel2004 I don't know why the installation fails and I can't reproduce the problem.
The install script and devcon.exe is from the XP-Pen drivers.
You could try this:
https://github.com/hawku/TabletDriver/wiki/FAQ#q-ive-installed-vmulti-driver-but-i-get-an-error-cant-open-vmulti-device

**Comment by Miguel2004** [comment]
That did not work, either.

**Comment by hawku** [comment]
@Miguel2004 The XP-Pen drivers doesn't work either?
I can't help with your problem. There is something wrong with your Windows installation that needs to be fixed.

**Comment by Saicooh** [comment]
- open remove_vmulti_driver.bat
- then open cmd and put bcdedit /set TESTSIGNING ON
- reboot and try installing again...

at least that worked for me :)

**Comment by semyuon** [comment]
> * open remove_vmulti_driver.bat
> 
>     * then open cmd and put bcdedit /set TESTSIGNING ON
> 
>     * reboot and try installing again...
> 
> 
> at least that worked for me :)

holy shit it actually worked
