### ISSUE TITLE
Dead link for XP-Pen Package (FAQ)

### ISSUE THREAD

**Issue by Qylwok** [hawku/TabletDriver#228]
Just to let you know that the XP-Pen package link on the FAQ for the question "Q: I've installed VMulti driver, but i get an error: "Can't open VMulti device"" is now dead : https://www.xp-pen.com/upload/download/20180130/XP-PenWin(20180130).zip

**Comment by Qylwok** [comment]
I found in my archives the executable, here is a dropbox link (ver. 1.4.4.180118) : https://www.dropbox.com/s/bboptym8yfeihk7/PentabletXPPEN1.4.4.180118.exe?dl=0

**Comment by hawku** [comment]
Thanks!
It also looks like that the the latest version of the XP-Pen driver (20180810) doesn't work with the TabletDriver v0.1.5
They have changed the data structure of the VMulti driver.

**Comment by hawku** [comment]
I have now updated the link
