### ISSUE TITLE
Tablet Drivers reset every time I reboot windows

### ISSUE THREAD

**Issue by ClickyOSU** [hawku/TabletDriver#231]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5.5 Devocub Edition

Tablet model: CTL-480

Every time I reboot my PC my tablet area defaults to 70, and it moves far left. It also resets my display to nothing instead of Display1.\

This is what the settings are now: https://imgur.com/a/xsk3qma

This is what happens after I reboot: https://imgur.com/a/aqmNRe7

**Comment by hawku** [comment]
@ClickyOSU You might have two different driver versions.
It seems that official version runs at startup and Devocub's doesn't.
