### ISSUE TITLE
Pressure sensitivity does not work

### ISSUE THREAD

**Issue by AceHysth** [hawku/TabletDriver#236]
I activate the option of windows ink in the drivers and nothing else works in the windows workstation, instead in Photoshop or Paint Tool Sai do not work but with the XP Pen drivers if it works with the windows ink activated

## Hardware/software information
Windows Version: Windows 10 Pro 10.0.17134

Tablet Driver version: 0.1.5

Tablet model: XP-PEN G640

**Comment by BYSTACK** [comment]
https://github.com/hawku/TabletDriver/issues/257, https://github.com/hawku/TabletDriver/issues/84
It doesn't work because photoshop and SAI use WinTab (not windows ink) which is not supported by this driver.
