### ISSUE TITLE
Can't set tablet area, always set to full area

### ISSUE THREAD

**Issue by mchgl18** [hawku/TabletDriver#237]
I've tried everything from #151  #102 and #1 , nothing works

## Hardware/software information
Windows Version: 
Windows 10
Tablet Driver version: 
TabletDriverV0.1.5
Tablet model: 
Xp-Pen G430S

**Comment by moosey2323** [comment]
i have a ctl-480 and it does the same thing

**Comment by hawku** [comment]
@mchgl18 Please, check the issue #301
