### ISSUE TITLE
Touch Input Support

### ISSUE THREAD

**Issue by georgejeno8** [hawku/TabletDriver#238]
Do you have any ideas on how to get the touch input on tablets that support it?  I tried using USBlyzer to look at the data from touch events, but I'm not really sure where to go from there.

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5

Tablet model: CTL-480

**Comment by hawku** [comment]
@georgejeno8 I don't think that touch support will be added to the driver.
Tablet buttons might added in the future, but the touch support has much lower priority.
