### ISSUE TITLE
XP PEN G430 Tablet not found

### ISSUE THREAD

**Issue by pytajnik2** [hawku/TabletDriver#24]
^help please

**Comment by pytajnik2** [comment]
i have same issue with new xp pen driver "XP-PenWin(20180130)", older driver works

**Comment by hawku** [comment]
@pytajnik2 Try to run the TabletDriverGUI as an administrator.

Are you sure that your tablet is G430 and not the newer model G430**S**?

Can you find tablet's HID device from the Windows Device Manager?
http://hwk.fi/TabletDriver/WacomHID.png, but the device instance path should start with `HID\VID_28BD`

**Comment by pytajnik2** [comment]
its g430 not g430s and i trying run as an admin
i can find talbet in usb section not HID section https://i.imgur.com/z8YWqSd.png
in the HID section, I have something like that https://i.imgur.com/p9PB1rx.png

**Comment by hawku** [comment]
@pytajnik2 There are at least two different XP-Pen G430 models. You have the older model that is not supported by this driver or XP-Pen's latest drivers. Check the issue #35

**Comment by hawku** [comment]
Duplicate of #35
