### ISSUE TITLE
disable_wacom_drivers not working

### ISSUE THREAD

**Issue by Xykeal** [hawku/TabletDriver#242]
Hello, I am trying to switch between wacom drivers and hawku drivers using the disable_wacom_drivers tool provided, but it is not working, I am getting a "Tablet Init Failed" message. The solutions linked in the FAQ don't help. If anyone could help, it would be really appreciated, thanks!

## Hardware/software information
Windows Version: Windows 10 Home

Tablet Driver version:  0.1.5

Tablet model: CTL-680

**Comment by cl8n** [comment]
same issue here, on Windows 10 Pro with a CTH-680

**Comment by hawku** [comment]
@Xykeal  @cl8n Disabling should work in the latest version.

**Comment by cl8n** [comment]
can confirm it works now, thank you very much!
