### ISSUE TITLE
The driver does not work with my tablet

### ISSUE THREAD

**Issue by NothinButNedd** [hawku/TabletDriver#243]
I know I am not using a compatible tablet with the driver but when I had first got it, it worked perfectly fine. I could change my area, I could switch to left hand mode, et cetera. But now it does not work.

## Hardware/software information
Windows Version: 
Windows 10 Home 64bit 
10.0.17134 Build 17134

Tablet Driver version: 
0.1.5
Tablet model: 
Veikk S640

**Comment by hawku** [comment]
VEIKK S640 support will be added in the next release.
