### ISSUE TITLE
Compatibility for Veikk S640 pls

### ISSUE THREAD

**Issue by SusKuN1337** [hawku/TabletDriver#247]
title says everything lul

## Hardware/software information
Windows Version: Windows 10 Pro

Tablet Driver version: xd

Tablet model:  Veikk S640

**Comment by MeguMisaka** [comment]
I would also like to have compatibility for Veikk S640, good tablet but I would like to see how well it would be with less input lag

**Comment by Joewomble1** [comment]
I too would like the veikk s640 to be added support for hawku.

**Comment by hawku** [comment]
VEIKK S640 support will be added in the next release.
