### ISSUE TITLE
I honestly don't know what's going on

### ISSUE THREAD

**Issue by qwirrrr** [hawku/TabletDriver#250]
Ok so I wanted to send a video but this website is retarded and it doesn't let me upload zip files although it says it supports it.
Anyways I downloaded the driver and whenever I use my tablet the cursor jumps up and down really fast (depending on the pen's position on the y-axis of the tablet the distance is different, higher means less distance)
## Hardware/software information
Windows Version: 
10 64-bit
Tablet Driver version: 
0.1.5
Tablet model: 
XP pen g430
However, I am using the pen from the Veikk s640 tablet (it works flawlessly without any drivers)

**Comment by YChvanov** [comment]
Two drivers is running at the same time most likely
