### ISSUE TITLE
My GUI (TD) wont stop saying "Driver Stopped! Restarting! Check Console!"

### ISSUE THREAD

**Issue by LoliLink** [hawku/TabletDriver#254]
I've been trying to fix the issue myself and it continues to say things like the title I put. I tried uninstalling all other drivers an installing the two links on the GitHub page. I ran the correct driver and did everything it asked me to do and it still isn't working. I even restarted my PC. I need help please contact me!!

## Hardware/software information
Windows Version: Windows 10 x64

Tablet Driver version: 0.1.5

Tablet model: CTH-480

**Comment by LoliLink** [comment]
THANKS FOR HELPING YOU GUYS SUCK AT YOUR JOB

**Comment by nomq1** [comment]
Did you run install_vmulti_driver.bat ?

**Comment by Banbeucmas** [comment]
> THANKS FOR HELPING YOU GUYS SUCK AT YOUR JOB

Thanks for being ignorant.
