### ISSUE TITLE
Deco 01 not reading.

### ISSUE THREAD

**Issue by satisnowflake** [hawku/TabletDriver#258]
Hello.
I have a XP-PEN Deco 01 tablet.
And your driver doesn't work with it.
Some people have the same issue, I think.
There's my startup *.txt file attached:
[startuplog.txt](https://github.com/hawku/TabletDriver/files/2472191/startuplog.txt)

Edited: Now I just tried to enter my ID of Deco 01 (first one; I have two versions of driver, but I uninstalled other drivers, it's strange). Here's a startup:
[startuplog.txt](https://github.com/hawku/TabletDriver/files/2472288/startuplog.txt)
And then I entered an ID of another driver version of Deco 01 (second one):
[startuplog.txt](https://github.com/hawku/TabletDriver/files/2472295/startuplog.txt)
It's not working at all.

## Hardware/software information
Windows Version: Windows 10 Professional x64.

Tablet Driver version: 0.1.5

Tablet info:
 • First one:
![11](https://user-images.githubusercontent.com/44084481/46858361-d18a4380-ce13-11e8-8dc2-06f1c971ff00.png)
• Second one:
![22](https://user-images.githubusercontent.com/44084481/46858369-d7802480-ce13-11e8-8339-ca02d50bb872.png)

Tablet model: XP-PEN Deco 01.

**Comment by hawku** [comment]
When did you purchase that tablet?
It seems like XP-Pen have made different DECO 01 models with different hardware/firmware.
Changing the `Tablet 0x28BD 0x0042 0xFF0A 0x0001` line to `Tablet 0x28BD 0x0902 0xFF0A 0x0001` should work if the tablet's firmware is similar to other XP-Pen models.

You could also try change the init report to: `InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00`

**Comment by satisnowflake** [comment]
Tablet was bought in the July, 15th.
As you can see, I have already tried to change the «Tablet» line.
It's working very strangeful: it's always «Windows Inc» mode without a cursor.
Changing the «InitReport» line didn't fix it too.
