### ISSUE TITLE
Compatibility for VEIKK S640

### ISSUE THREAD

**Issue by OGValiente** [hawku/TabletDriver#260]
Currently, the driver doesn't recognize this tablet and it would be awesome if we can get an update regarding this. This is a newly trending tablet.

## Hardware/software information
Windows Version: Windows 10 / 64 Bit

Tablet Driver version: 1.0.0.0

Tablet model: VEIKK S640

**Comment by YChvanov** [comment]
Copy of #247 and #243

**Comment by hawku** [comment]
VEIKK S640 support will be added in the next release.
