### ISSUE TITLE
PLEASE MAKE COMPATIBLE WITH G640S

### ISSUE THREAD

**Issue by ohn123** [hawku/TabletDriver#262]
The g640s driver has a terrible problem where if you move the cursor and stop the cursor moves a bit after that.

Thanks

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version:  

Tablet model: XP Pen G640s

**Comment by YChvanov** [comment]
Copy of #261, which has solution

**Comment by SilentNutMan** [comment]
I agree with you. Got the G640S a few days ago. He has a terrible driver.

**Comment by hawku** [comment]
@ohn123 XP PEN G640s support will be added in the next release.
