### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by tRbaXn** [hawku/TabletDriver#263]
Could you please make a Mac version of this driver please that'd be absolutely amazing just like you <3

**Comment by Banbeucmas** [comment]
Prob he will or someone who pick this up will make one in the future. But not really now, his accont hasn't seen any activities for over 3 months now

**Comment by tRbaXn** [comment]
Okay, thank you for telling me that <3

**Comment by Banbeucmas** [comment]
@hawku This issue is open anyway so I will also request for Linux support.

Maybe not TabletDriver GUI itself but make a CLI that can hook into the excisting wacomdriverlib that was built for Linux
