### ISSUE TITLE
Two drivers

### ISSUE THREAD

**Issue by raresica1234** [hawku/TabletDriver#268]
I can't get the pressure to work, I tried Windows Ink mode, so I was wondering if it's possible to have 2 drivers coexist, this driver and the one from xp pen?

## Hardware/software information
Windows Version: Windows 10 Pro - 1803

Tablet Driver version: 0.1.5

Tablet model: XP Pen G430S

**Comment by YChvanov** [comment]
If someone will search this topic again, i can suggest [my solution](https://raw.githubusercontent.com/YChvanov/batch_scripts/master/xppen.bat), although it's not perfect
