### ISSUE TITLE
Screen map isn't correctly mapped  in the tablet area.

### ISSUE THREAD

**Issue by NRchaos** [hawku/TabletDriver#270]
## Hardware/software information
Windows Version: 7

Tablet Driver version:  Tablet Driver V0.1.5

Tablet model: XP-PEN Star G430S

Sorry, my English is not good, can't correctly explain the problem.
I set  tablet area ( width 55 mm height 49 mm X 74.9 mm Y 51.7 mm )
That  tablet area should be on central, but I don't know why it was on bottom right corner.
Then tablet pen can't work on this tablet area and other area.
If I want to make tablet area work on central, must set the tablet area on upper left corner and reduce tablet area.

**Comment by YChvanov** [comment]
See #196

**Comment by NRchaos** [comment]
thank you !

**Comment by YChvanov** [comment]
Close the issue then
