### ISSUE TITLE
Drivers work, but not right after TabletDriverGUI is opened.

### ISSUE THREAD

**Issue by the-reverbcs** [hawku/TabletDriver#271]
I open up the tablet driver GUI, and I have to wait around 5 minutes before I can start using my tablet. Right after I open up the driver GUI, my tablet is unresponsive and will not work at all. 

After around 5 minutes, my mouse cursor will go up to the top of my screen, and then will start working. Any known issues about this and any potential fixes for it?

## Hardware/software information
Windows Version: Windows 10 Pro, 64x bit.

Tablet Driver version: 1.5

Tablet model: CTL-4100

**Comment by Banbeucmas** [comment]
Try to restart the driver

For some hecky reason. I hard to keep my Discord open for it to actually works...
