### ISSUE TITLE
tablet didn't work after update nvidia driver

### ISSUE THREAD

**Issue by ShounenX** [hawku/TabletDriver#272]
after i update my nvidia driver to416.34
my tablet can't work
and when i connect the usb of tablet
the indicator light on the left side of my tablet start to twinkling
after about 5 times, it stopped and my tablet can't work at all
how to solve this problem

## Hardware/software information
Windows Version: windows10 x64

Tablet Driver version: v0.1.5

Tablet model: CTL-480

**Comment by hawku** [comment]
@ShounenX I think that is USB problem, so the driver can't fix that.
