### ISSUE TITLE
Full tablet area

### ISSUE THREAD

**Issue by sevenbbt** [hawku/TabletDriver#274]
I have unistalled pentablet driver before running v_multi
I have also changed my tablet area but somehow it still uses up my full tablet area, just.. the speed was different, it did not disable any of the unwanted tablet area.
I have applied, saved, and restarted the driver, still nothing. 

## Hardware/software information
Windows Version: 10 Home

Tablet Driver version: v0.1.5

Tablet model: XP-Pen G430s
![image](https://user-images.githubusercontent.com/44673146/47854738-7b5e5e00-de1d-11e8-89db-023634bec354.png)

**Comment by BYSTACK** [comment]
G430s is not in the supported tablets list. though there is PR #196

**Comment by hawku** [comment]
@sevenbbt Please, check the issue #301
