### ISSUE TITLE
veikk s640 support 

### ISSUE THREAD

**Issue by noel1234noel** [hawku/TabletDriver#275]
## Hardware/software information the regular driver for it sucks and wont work at all so please hurry and make it compatible with this awesomeness
Windows Version: 10

Tablet Driver version: 

Tablet model: veikk s640

**Comment by OGValiente** [comment]
#260 #243 #247 
We are still waiting... Not sure if they're actively working on this driver though.

**Comment by IsaacElenbaas** [comment]
https://www.reddit.com/r/osugame/comments/9wow87/veikk_s640_low_latency_drivers_are_on_the_way/e9moi3r
Currently adding driver support won't do much for performance, it'll just be a substitute. Hawku's working on it.

**Comment by hawku** [comment]
VEIKK S640 support will be added in the next release.
