### ISSUE TITLE
Wacom CTL-490 Sensivity

### ISSUE THREAD

**Issue by Roblah** [hawku/TabletDriver#278]
Sometimes the sensivity of my tablet is more higher compared to my area, and sometimes work really good. I dont know what happen, any solution?

## Hardware/software information
Windows Version: Windows 10 Pro

Tablet Driver version: v0.1.5

Tablet model: Wacom CTL-490

**Comment by qwuzzy** [comment]
Is there no way to disable the smoothing? This is my main problem with the tablet and this software doesn't fix that.

**Comment by hawku** [comment]
Hardware smoothing in hover can't be disabled.
Just tape the pen tip down to trick the tablet to be always in dragging mode.
