### ISSUE TITLE
CTE-440 Support (Config Provided)

### ISSUE THREAD

**Issue by Faithy3** [hawku/TabletDriver#279]
So I spent a few hours manually configuring my CTE-440 for the drivers, and I'm posting them here just in case anyone needs them.
#
# Wacom CTE-440 Custom
#
Tablet 0x056A 0x0015 0x000D 0x0001
Name "Wacom CTE-440"
ReportLength 9
DetectMask 0x00
MaxX 10000
MaxY 7500
MaxPressure 511
Width 127.6
Height 92.8
InitFeature 0x02 0x02

## Hardware/software information
Windows Version: 10.0.17134.345

Tablet Driver version: 0.1.5

Tablet model: CTE-440

**Comment by hawku** [comment]
@Faithy3 I generated this configuration from the Wacom linux driver code:
```
# Wacom CTE-440
Tablet 0x056A 0x0015 0xFF0D 0x0001
Tablet 0x056A 0x0015 0x000D 0x0001
Name "Wacom CTE-440"
ReportLength 8
DetectMask 0x80
MaxX 10208
MaxY 7424
MaxPressure 511
Width 127.600
Height 92.800
InitFeature 0x02 0x02
```

Can you test that configuration?
