### ISSUE TITLE
ERROR I Can't save my custom config

### ISSUE THREAD

**Issue by Iscarlat9** [hawku/TabletDriver#281]
## Hardware/software information
Windows Version: Windows 10 64Bits

Tablet Driver version: latest

Tablet model: CTH-472
![screenshot_1](https://user-images.githubusercontent.com/45007224/48420086-ba0ae700-e740-11e8-974d-0a1e574054b8.png)

I can't save my own config anymore idk why, now every time that i open the driver it starts with the default config

**Comment by Kiewaii** [comment]
> Well, can you create files in that folder?

Please help me, i cant use the driver because of that. How can i change that? How can I give myself the permission?

**Comment by hawku** [comment]
@Kiewaii How did you unzip the driver to a folder that you don't have permissions to write?
Maybe try another folder.

**Comment by Powerfulwho1783** [comment]
Make sure that you put the folder or zip file on your desktop then open
