### ISSUE TITLE
CTL-472 Unusual shake

### ISSUE THREAD

**Issue by tokeyie** [hawku/TabletDriver#282]
I'm aware of the usual shake in the driver but the shake I'm having makes my cursor jittery and destroys my aim, technically making the game unplayable. It prevents me from jumping and making a proper line would make it zigzag for no reason, it also takes more effort to stabilize the cursor. I've never had this issue with my old tablet before and I'm used to hovering, this tablet I have is new. I've tried the devo variation with no avail, same thing happens with dragging. I've noticed how players like firebat92 who use this driver doesn't have the shake at all and making my pen closer to the tablet doesn't make any difference. The only time I had a similar case to this is when my old tablet's pen nib was broken. Wasn't it suppose to be smooth regardless of the shake?

Tablet model: CTL-472

**Comment by hawku** [comment]
@tokeyie That sounds like a hardware problem. 

You can run a tablet benchmark from the console tab. Right click the console output and click "Run Benchmark". Hold the pen stationary on top of the tablet when the benchmark is running.

Run the test few times and check if your results match with my results:
`Tablet(Wacom CTL-472) Noise(0.030 mm x 0.060 mm) Packets(200)`
`Tablet(Wacom CTL-472) Noise(0.060 mm x 0.030 mm) Packets(200)`
`Tablet(Wacom CTL-472) Noise(0.050 mm x 0.070 mm) Packets(200)`

Try to run the test in different areas of the tablet.   Higher hover height also causes more noise/shaking.
