### ISSUE TITLE
G640 & antichatter

### ISSUE THREAD

**Issue by JohnathanKeen** [hawku/TabletDriver#285]
Hi,

When I enable antichatter while using my G640, it doesn't seem to be doing anything and as soon as I start using mouse, the cursor position is locked to the last tablet position. 

This does not happen if I enable antichatter with my CTL-480,

I have installed both vmulti driver and huion driver just in-case, still nothing. Happens purely with anti-chatter.

![2018-11-20_23-10-35](https://user-images.githubusercontent.com/45221516/48818425-49079880-ed19-11e8-9286-bfd7e7d2b745.gif)

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5.5 Devocub Edition

Tablet model: XP-PEN G640

**Comment by hawku** [comment]
@JohnathanKeen I think that the XP-PEN G640 doesn't need any antichatter or smoothing from the drivers. That tablet does the pen position smoothing and noise suppression on the hardware. Hardware smoothing causes already enough of latency, so I wouldn't recommend using any additional filters.

**Comment by JohnathanKeen** [comment]
> @JohnathanKeen I think that the XP-PEN G640 doesn't need any antichatter or smoothing from the drivers. That tablet does the pen position smoothing and noise suppression on the hardware. Hardware smoothing causes already enough of latency, so I wouldn't recommend using any additional filters.

I agree with you, just thought I'd share since it seems to be an actual bug. Up to @Devocub if he's willing to investigate it or not.

Thanks for the replies.
