### ISSUE TITLE
CTL-671 hardware smoothing?

### ISSUE THREAD

**Issue by merlinch** [hawku/TabletDriver#286]
Does CTL-671 has a hardware smoothing? I'm confused because no one has ever discussing about this

## Hardware/software information
Windows Version: 10

Tablet Driver version: -

Tablet model: -

**Comment by hawku** [comment]
This is not an issue with this tablet driver.

I don't think that the older Wacom tablets had hardware smoothing. CTL-471 doesn't have hardware smoothing.

The CTL-490 does have hardware smoothing when the pen tip is not pressed down.
