### ISSUE TITLE
CTL-4100 not working

### ISSUE THREAD

**Issue by Slowerosu** [hawku/TabletDriver#287]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.1.5

Tablet model: CTL-4100 USB

**Comment by chrisEsk** [comment]
Attach the included message in the console tab. Mine's working fine:

![image](https://user-images.githubusercontent.com/1473990/48882245-e7116680-edde-11e8-889a-c565f749d0a1.png)
