### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by Eranuwu** [hawku/TabletDriver#288]
VCRUNTIME140.dll is missing

https://i.imgur.com/OaZiyyV.png

## Hardware/software information
Windows Version: Windows 10 Pro 64bit 

Tablet Driver version: v 0.1.5 

Tablet model: CTH 470

**Comment by hawku** [comment]
You need to install the C++ runtime library.
https://github.com/hawku/TabletDriver#installation
https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by Eranuwu** [comment]
I HAVE IT DOEEEEE

**Comment by RisedSky** [comment]
http://www.telecharger-dll.fr/dll-vcruntime140.dll.html

Put the dll in `C:\Windows\System32`

If you use 64bits put **too** in `C:\Windows\SysWOW64\`

**Comment by hawku** [comment]
@Eranuwu I just checked the picture you provided: https://i.imgur.com/OaZiyyV.png
That error isn't for this driver... That is an error for iCUE.exe, which is Corsair Utility Engine...
