### ISSUE TITLE
Tablet tapping not working properly

### ISSUE THREAD

**Issue by KSN24** [hawku/TabletDriver#291]
When the input of my pen tip is enabled, it just keeps randomly activating (pressing mouse1 / left mouse button) even if it is not supposed to, for example when I'm hovering, also actual pressing sometimes doesn't work. 

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.5

Tablet model: CTH-480

**Comment by hawku** [comment]
@KSN24 Does that happen with the official Wacom drivers?

**Comment by KSN24** [comment]
@hawku no, that's why I opened an issue. I considered going back to wacom drivers so I can use it again, but I decided to check if you were able to fix my issue instead.

**Comment by hawku** [comment]
@KSN24 Maybe the pen nib is stuck so it will apply little bit of pressure to pressure sensor?
Try another pen nib or reinsert the current nib.

You can also try to add this command to commands tab: `ClickPressure 100`
That will set the pen tip click pressure limit to about 10% of maximum pressure.

**Comment by KSN24** [comment]
pennip wasn't actually stuck, but reinserted it and now it seems to work? don't get it to be honest.

eitherway, thanks for your advice, it now works again!
