### ISSUE TITLE
Driver settings not working as intended

### ISSUE THREAD

**Issue by JaViLuMa** [hawku/TabletDriver#292]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version:  0.1.5

Tablet model:  Huion H420

Drivers sometimes (like 3-5 times a day) just stop working, cursor doesn't move and if it does move it is inverted (I am left handed) from the way it should be moving.

Restarted drivers like 20+ times and the issue still happens.

**Comment by hawku** [comment]
@JaViLuMa What does it say in the console tab when the tablet doesn't work correctly?
Upload the `startuplog.txt` from the drivers folder to here when the problem occurs next time.

**Comment by JaViLuMa** [comment]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/2636385/startuplog.txt)

Here is the log. The cursor goes to the top left of the screen in osu! and the cursor is inverted.

**Comment by hawku** [comment]
@JaViLuMa Does that happen with the latest version (0.2.1)?

**Comment by JaViLuMa** [comment]
@hawku I don't seem to have any issues this last 2 weeks.
