### ISSUE TITLE
can you make a command list

### ISSUE THREAD

**Issue by Zypes** [hawku/TabletDriver#294]
i cant find one

**Comment by xyning** [comment]
i think all commands can be found in **[this file](https://github.com/hawku/TabletDriver/blob/master/TabletDriverService/ProcessCommand.cpp)**

**Comment by hawku** [comment]
@Zypes I will make some documentation about commands in some day, but now you can find commands from here: https://github.com/hawku/TabletDriver/blob/6cdcc503405f262bbe1ce8491c2ea442115e42d4/TabletDriverService/CommandHandler.cpp#L61

**Comment by hawku** [comment]
@Zypes The latest version will provide a list of commands when you press tab in the console input field.
