### ISSUE TITLE
Will this affect other tablet drivers

### ISSUE THREAD

**Issue by kuwoh** [hawku/TabletDriver#296]
So basically i have two graphics tablets one cth - 470 (wacom) and the other is an artist 12. Will this affect the artist 12? or would it only modify my wacom drivers

## Hardware/software information
Windows Version: 7 - 64bit

Tablet Driver version: 

Tablet model:

**Comment by hawku** [comment]
@kuwoh The driver will affect both tablets. You would have to uninstall Wacom and XP-PEN drivers.
