### ISSUE TITLE
Tablet disconnected = mouse on the top left

### ISSUE THREAD

**Issue by RisedSky** [hawku/TabletDriver#297]
When you disconnect your tablet, the driver module is putting the mouse on the top left of the screen, here is a RECORD showing the issue, when CLOSING it, it doesn't do it again.
But when opening it, it does the problem.
https://youtu.be/xzj22Oc_XPQ

## Hardware/software information
Windows Version: **Windows 10 Home 1809 version**

Tablet Driver version: **0.2 (the latest actually 08/12/2018 (FR) )**

Tablet model: **HUION 420**

**Comment by YChvanov** [comment]
#266...

**Comment by hawku** [comment]
@RisedSky This will be fixed in the next release.

**Comment by RisedSky** [comment]
> @RisedSky This will be fixed in the next release.

Thanks!
