### ISSUE TITLE
Anti-smoothing filter values for VEIKK S640

### ISSUE THREAD

**Issue by Valientedev** [hawku/TabletDriver#303]
First of all, thanks for making the driver compatible with S640, you can easily feel the difference for input lag reduction.
About the issue, S640 is not listed in anti-smoothing filter, I set '0.5' to Shape and '3.5' to Compensation but don't know which values would fit the best. Does anybody have a suggestion on this?

## Hardware/software information
Windows Version: Win10 Home

Tablet Driver version: Hawku Custom v2.1

Tablet model: VEIKK S640

**Comment by hawku** [comment]
@OGValiente Shape 0.5 and compensation 3.5 is a good starting point.
Increase the latency compensation value by 0.5 until the cursor feels too fast or there are too much shaking.

You can also enable the noise reduction filter to combat shaking at high latency compensation values.
