### ISSUE TITLE
Thanks! Works even tho Tablet is not supported

### ISSUE THREAD

**Issue by lolsoftlight** [hawku/TabletDriver#304]
I just have an old CTH-460 (That cheap pen and touch thing) 
I never liked it since it feels horrible slow with the official drivers, wich are super old and bad overall. You dont even have options to set values for tablet area and stuff.

Installed.. and it works great.

It feels like a complete new tablet with these drivers really :O So much faster and more responsible and more options.  thanks 

![tablet1](https://user-images.githubusercontent.com/18228511/49960447-79a1b300-ff10-11e8-8d08-1f40b35c4ab3.JPG)
![tablet2](https://user-images.githubusercontent.com/18228511/49960448-7a3a4980-ff10-11e8-9444-3beae6ba3d25.JPG)

**Comment by riley-badour** [comment]
this tablet is supported  and you said there no problems unless there is any you should close this issue  im guessing that this tablet is not displayed in the devices supported list
