### ISSUE TITLE
Buttons from 0.2.1 imports wrongly in 0.2.2

### ISSUE THREAD

**Issue by YChvanov** [hawku/TabletDriver#306]
They are importing as keyboard keys, but mouse

0.2.1: ![image](https://user-images.githubusercontent.com/25438100/50052382-3e7fc980-0134-11e9-9a19-4dfb0b84c167.png)
0.2.2:![image](https://user-images.githubusercontent.com/25438100/50052378-27d97280-0134-11e9-877d-b43afbe29a6f.png)

## Hardware/software information
Windows Version: 10 (1607)

Tablet Driver version: 0.2.2

Tablet model: XP-Pen G640

**Comment by hawku** [comment]
@YChvanov Configuration import/export can sometimes work between different driver versions, but not when there are larger changes to the configuration file.
