### ISSUE TITLE
Using 2 drivers alternately

### ISSUE THREAD

**Issue by idonthaveideaforusername** [hawku/TabletDriver#308]
Is it possible to use Wacom driver for drawing and switch for this driver to play osu without uninstalling any of these?

**Comment by hawku** [comment]
@idonthaveideaforusername Some Wacom tablet can be used while the Wacom drivers are installed.
Check `config\tablet.cfg` if your tablet is supported.

Run `tools\DisableWacomDrivers.bat` to disable Wacom drivers.

**Comment by idonthaveideaforusername** [comment]
I don't know exactly how this tablet.cfg works but I'll try the disable function when I find the time.
