### ISSUE TITLE
Cursor suddenly clips to the edge of the screen.

### ISSUE THREAD

**Issue by nerrowcool** [hawku/TabletDriver#31]
Video:
[https://puu.sh/zHXU2/c572826d73.mp4](https://puu.sh/zHXU2/c572826d73.mp4)
[https://puu.sh/zHYb0/9872c3367d.mp4](https://puu.sh/zHYb0/9872c3367d.mp4)

Setting:
![tabletdrivergui_2018-03-15_13-52-37](https://user-images.githubusercontent.com/23612631/37446481-29dd1c22-2858-11e8-8bcc-0d8b9b16dbc4.png)

As you see, the cursor suddenly "teleported" to the edge of my screen after it reached a certain position and sometimes stuck at there for a while. It causes inconvenience and greatly affects my daily use of tablet.

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.0.14

Tablet model: CTH-480

**Comment by nerrowcool** [comment]
This situation still happens in other area setting.

**Comment by nerrowcool** [comment]
Also, the wacom area setting automatically changed **"Top: 0, Bottom: 7335, Left: 0, Right: 13040"** to **"Top: 1, Bottom: 7336, Left: 0, Right: 13040"** while 13040/7335 is 16/9.

**Comment by ErzaScarlettttt** [comment]
try minimizing the gui instead of closing it

**Comment by hawku** [comment]
@nerrowcool Does that happen with the official Wacom drivers?
