### ISSUE TITLE
I might be really stupid but where is the apply button?

### ISSUE THREAD

**Issue by shibou3** [hawku/TabletDriver#310]
I'm trying to apply the area but idk if something changed in the new version
https://puu.sh/CjDRB/25f404cf39.jpg

## Hardware/software information
Windows Version: 

Tablet Driver version: 

Tablet model:

**Comment by hawku** [comment]
@shibou3 Old version did have an apply button but it was almost same as save button.
I removed the apply button and the "Save settings" now does apply settings to driver and store them to config.xml.
You can also press CTRL+S to save the settings.

**Comment by shibou3** [comment]
@hawku I'm doing both (pressing button and control S) but it's not working
