### ISSUE TITLE
Is there any forum, subreddit or something about this custom driver?

### ISSUE THREAD

**Issue by shibou3** [hawku/TabletDriver#311]
I was thinking about ask other ctl490 users what config they would or use in anti-smoothing filter but I couldn't find any place so.

## Hardware/software information
Windows Version: 

Tablet Driver version: 

Tablet model:

**Comment by hawku** [comment]
@shibou3 There is a reddit post about those new filters: https://www.reddit.com/r/osugame/comments/a32z8l/tabletdriver_02_released_feedback_needed/
