### ISSUE TITLE
TabletDriverGUI wont appear

### ISSUE THREAD

**Issue by Soraxel** [hawku/TabletDriver#312]
## Hardware/software information
Windows Version: Windows 10 Education Version 1803

Tablet Driver version: 0.1.5/0.2.3

Tablet model: HUION 420

## Issue
TabletDriverGUI.exe appears in the taskbar then disappears when I hover the mouse over the icon. I can't edit the tablet area or anything. It used to work but it stopped working recently out of nowhere. at first, it stopped working while using driver version 0.1.5 then I updated the driver to 0.2.3 and I'm still having the same problem.
I tried what Zeny97 did here but still didn't work.
https://github.com/hawku/TabletDriver/issues/54
here is a video of it:
https://youtu.be/TqpiHl1grhk

**Comment by Soraxel** [comment]
oh sorry I asked a friend to do this for me and he dragged it instead of sending a shortcut
but it's the same as if it's in the directory, I get the same results

**Comment by Soraxel** [comment]
I excluded the whole folder in windows defender and I'm still getting the same problem.
and where can I find Windows Event Viewer? first time hearing of it

**Comment by Soraxel** [comment]
![image](https://user-images.githubusercontent.com/41630856/50366189-51a5f580-0589-11e9-8b7d-86605985aff6.png)
this one?
how do I use it?

**Comment by hawku** [comment]
@Soraxel Select Windows Logs -> Application and look if there are any TabletDriverGUI errors.

**Comment by Soraxel** [comment]
The source should be TabletDriverGUI?
or should I use the Find option?

**Comment by hawku** [comment]
@Soraxel You can use Find option, but source might be ".NET Runtime" or "Application Error"

**Comment by Soraxel** [comment]
alright, ill check on it tomorrow because I don't have access to the computer now so no need to expect a response today and I don't want to take from your time waiting from me. I'll catch you up tomorrow hopefully.
