### ISSUE TITLE
How do i use a config i made for a huion driver on this driver

### ISSUE THREAD

**Issue by Yotens** [hawku/TabletDriver#313]
How do i use a config i made for a huion driver on this driver?

## Hardware/software information
Windows Version: 10 Home

Tablet Driver version: Newest as of 12/21/18

Tablet model: H420 Huion

**Comment by hawku** [comment]
@Yotens Are you even sure that you have correctly setup the tablet area in Huion drivers?
It is almost impossible to configure the tablet area correctly in Huion drivers without using calculator or some external tool.

Just measure the old tablet area width with a ruler on a tablet's surface.
Type that measurement in millimeters to the TabletDriver and make sure that force aspect ratio is enabled.
