### ISSUE TITLE
How do you make it work(install) with Veikk S640 please?

### ISSUE THREAD

**Issue by olcatt** [hawku/TabletDriver#315]
Code Execution cannot proceed because MSVCP140.dll was not found. Reinstalling may Fix the problem
^
this thing appears

## Hardware/software information
Windows Version: win10 pro

Tablet Driver version: 2.3

Tablet model: Veikk s640

**Comment by riley-badour** [comment]
Please read before you create a issue the solution is under the Installation the very fist step is there
https://github.com/hawku/TabletDriver/blob/master/README.md#installation

**Comment by olcatt** [comment]
> Please read before you create a issue the solution is under the Installation the very first step is there
> https://github.com/hawku/TabletDriver/blob/master/README.md#installation

i did all those things it doesn't seem to work.
i used a previous version of this and it worked on my huion but it doesn't seem to work on my veikk
those are from an older pc btw so i think i might have missed something, probably the step one
sorry for the idiotic question

**Comment by olcatt** [comment]
yeah i'm an idiot
i really missed the first step
