### ISSUE TITLE
PLZ SUPPORT CTE-460

### ISSUE THREAD

**Issue by SanjeninNagi** [hawku/TabletDriver#316]
## Hardware/software information
Windows Version:  10

Tablet Driver version: 2.3.1

Tablet model: CTE-460 NOT SUPPORT

PLZ SUPPORT PLZ :>>>>>

**Comment by hawku** [comment]
@SanjeninNagi PLZ TEST THIS CONFIGURATION:
```
# Wacom CTE-460
HIDTablet 0x056A 0x006A 0xFF0D 0x0001
HIDTablet 0x056A 0x006A 0x000D 0x0001
Name "Wacom CTE-460"
ReportLength 8
DetectMask 0x80
MaxX 14760
MaxY 9225
MaxPressure 1023
Width 147.600
Height 92.250
InitFeature 0x02 0x02
```
Add it to the end of the `config\tablet.cfg` file.
