### ISSUE TITLE
Not being able to save

### ISSUE THREAD

**Issue by lassedds** [hawku/TabletDriver#318]
I am havingproblems with saving it won't let me save it just says make sure that you can svae in tabletdriverv0.2.3 directory

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: Huion H420

**Comment by hawku** [comment]
@lassedds Can you create or edit files in the TabletDriver folder?
Where did you unzip the driver?

**Comment by lassedds** [comment]
I unzipped unto my desktop and yes i can do that

Den tir. 25. dec. 2018 kl. 23.13 skrev Mikko Jaakkola <
notifications@github.com>:

**Comment by hawku** [comment]
@lassedds Desktop is not a correct place to store files and install applications.
Unzip it to an another folder, for example `C:\Temp\TabletDriver`
