### ISSUE TITLE
Random black lines start to appear when i draw near a rectangular border.

### ISSUE THREAD

**Issue by SilentThorns** [hawku/TabletDriver#321]
## Hardware/software information
Windows Version: 

Tablet Driver version: TabletDriverV0.2.3

Tablet model: XP-PEN Star G640

[https://imgur.com/a/6TaRIiu](url)

**Comment by hawku** [comment]
@SilentThorns Does that happen with the official drivers?
Does that only happen in middle of the tablet area?
I can't reproduce that with my G640, so it might be a hardware problem.

**Comment by riley-badour** [comment]
I cannot reproduce that either on My g430s weird its like its giving a false x and y varible that lands at 0 great to have some some debuging info. Like startuplog.txt Also what happen swith stock drivers does it do the same.

**Comment by riley-badour** [comment]
Its like hawku said it could be a hardware problem
That what it seems to be if it happens on stock drivers aswell.

**Comment by Devocub** [comment]
It's Paint.NET problem, but in latest version (4.2.4) it is fixed
![image](https://user-images.githubusercontent.com/2735824/65655572-566e6d00-e025-11e9-9bbf-c050dd10df35.png)
