### ISSUE TITLE
Area/Map settings have no effect

### ISSUE THREAD

**Issue by Altrentorae** [hawku/TabletDriver#323]
Today I installed these drivers and they appear as expected, tablet is recognised etc. but when I change the screen mapping and the tablet area, nothing actually happens
http://puu.sh/CoY9I/f4f49559a7.png
The representation doesn't match the actual mapping as I can still reach the left and right monitors; the tablet also doesn't appear to be restricted to the area I set, as the lower right region which shouldn't do anything still moves the cursor as if set to full area. Any solutions?

## Hardware/software information
Windows Version: Windows 10 Home ver 10.0.17134 Build 17134

Tablet Driver version: 0.2.3

Tablet model: Wacom CTL-480

**Comment by Altrentorae** [comment]
I was almost certain I uninstalled them before hand.
When I uninstall from device manager the tablet stops working and TabletDriverGUI fails to connect to the tablet. If I then remove and re-insert the usb the tablet turns back on, and TabletDriverGUI recognises it, but the Wacom Tablet thing in the device manager seems to reappear. I'm not sure what to do from here, as I couldn't find another way to uninstall the Wacom Drivers

**Comment by hawku** [comment]
You can clearly see that TabletDriver is detecting Wacom driver filter device and not the actual tablet device, so it says (Wacom drivers installed) in the window title.
You have to somehow remove the Wacom driver device. Check if there are some extra Wacom devices in the device manager's human interface devices.
I had this problem once with CTH-480 and I only had to uninstall one driver device and selected  "Delete the driver software for this device".

**Comment by Altrentorae** [comment]
Issue solved, now works perfectly.
Was caused by the files not getting removed for some strange permission error reason. Didn't know that at first as it just caused the uninstall to fail

Thanks for your quick response, very commendable development
