### ISSUE TITLE
XP-Pen G640S - Cursor keeps moving when it should be stopped on slow movements only!

### ISSUE THREAD

**Issue by Noah0302v2** [hawku/TabletDriver#324]
My cursor keeps moving when the pen is stopped on slow movements only, jumping is fine!

I reinstalled the drivers and even used a different USB cable but this keeps happening. At first I did not really notice it but now I cant play slow parts of any map because of it.

I also tried different Driver versions but I am currently using the one stated below.

## Hardware/software information
Windows Version: Win 10 Pro

Tablet Driver version: TabletDriverV0.2.3

Tablet model: XP-Pen G640S

**Comment by hawku** [comment]
@Noah0302v2 That is a feature of G640S hardware. It will also happen with the official drivers.

**Comment by Noah0302v2** [comment]
Thanks for the reply!


I just got confused, because the tablet was advertised as an osu! tablet and this feature is the only thing holding it back from being my favourite osu tablet of all time.

 

Have a nice day.

Noah


Gesendet: Sonntag, 30. Dezember 2018 um 13:16 Uhr
Von: "Mikko Jaakkola" <notifications@github.com>
An: hawku/TabletDriver <TabletDriver@noreply.github.com>
Cc: Noah0302v2 <skribek@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [hawku/TabletDriver] XP-Pen G640S - Cursor keeps moving when it should be stopped on slow movements only! (#324)


@Noah0302v2 That is a feature of G640S hardware. It will also happen with the official drivers.
