### ISSUE TITLE
Wacom CTL-4100 (Wacom drivers installed) cant change tablet area??

### ISSUE THREAD

**Issue by Anderzs** [hawku/TabletDriver#326]
## Hardware/software information
Windows Version: 10

Tablet Driver version: v. 0.2.3

Tablet model: Wacom CTL-4100

The problem is that i click the button "Restart Driver" and it restarts and says "Connected to Wacom CTL-411 (Wacom drivers installed)" and thats fine right, but then i try and change the area and press save settings but nothing happens and i have the default area for my wacom tablet which is the whole tablet

I tried looking in the console but nothing suspicious seemed to pop up

[The startuplog is here startuplog.txt](https://github.com/hawku/TabletDriver/files/2718983/startuplog.txt)

**Comment by hawku** [comment]
@Anderzs The problem is that you have Wacom drivers installed.
You can't use both drivers at the same time.

**Comment by Anderzs** [comment]
I cant possibly find any trace of any wacom drivers on my computer and it still tells me that i have Wacom drivers installed

**Comment by Anderzs** [comment]
What files does the software look for when deciding if the tablet has drivers installed? 

Or how does it even look for it?
