### ISSUE TITLE
Mouse inverted

### ISSUE THREAD

**Issue by TLI1233** [hawku/TabletDriver#336]
## Hardware/software information
Windows Version: Windows 10 64-bit

Tablet Driver version: 
0.2.3
Tablet model: Wacom CTL-490

My up and down are inverted, every time I move the pen up, it moves down, and vice versa, I've tried roatating it, just for it to flip horizontally, I'm out of ideas.

**Comment by hawku** [comment]
@TLI1233 Does it do that in every mode (Absolute, Relative, Windows Ink and SendInput)?

**Comment by TLI1233** [comment]
It's all fixed now, just had to reboot, thanks for answering anyways ^^
