### ISSUE TITLE
Star G640 not working on Hawku

### ISSUE THREAD

**Issue by Vaf167** [hawku/TabletDriver#341]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: Star G640

Hello everyone, im having serious issues with my tablet since i cant use hawku with the G640 the pen just dont moves when moving it. 
Any kind of help will be appreciated 
Regards, Vaf
![73d84b03f8b42a84bfbcda2c144e25c8](https://user-images.githubusercontent.com/46717907/51189235-5dea4d80-18be-11e9-80b9-f600714c42ed.png)

**Comment by hawku** [comment]
@Vaf167 Does it work with the official XP-Pen drivers?
Does the cursor move if you use other modes than Absolute?
Does it output tablet movement data to console if you enable the debug checkbox at the bottom?

**Comment by Vaf167** [comment]
Hi! It does work with xpen drivers and dont know why but although relative works fine the debug mode works really well but when using absolute nothing occurs

**Comment by hawku** [comment]
@Vaf167 You have wrong vmulti driver installed by the XP-Pen driver installer.
Uninstall and reinstall the vmulti driver.
