### ISSUE TITLE
How to remove TabletDriver

### ISSUE THREAD

**Issue by OgnistyPoland** [hawku/TabletDriver#342]
Hello, how to uninstall TabletDriver? I need to start remove_vmulti_driver.bat or what? 
I wanted to test the original drivers from xp-pen, and I don't know if I can use two drivers at the same time

## Hardware/software information
Windows Version: Windows 10 Pro 64-bit

Tablet Driver version: 0.2.3

Tablet model: XP-Pen G460

**Comment by hawku** [comment]
https://github.com/hawku/TabletDriver#uninstallation
