### ISSUE TITLE
Every time i put up the pen from the tablet, cursor goes top left

### ISSUE THREAD

**Issue by Skopega** [hawku/TabletDriver#347]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.2.3

Tablet model: MTE-450

**Comment by hawku** [comment]
@Skopega I need more information about the problem.
You should record a debug log: https://github.com/hawku/TabletDriver/issues/340#issuecomment-453816344

Post the `debug_*.txt` and `startuplog.txt` to here.

**Comment by Skopega** [comment]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/2796766/startuplog.txt)
[debug.txt](https://github.com/hawku/TabletDriver/files/2796768/debug.txt)

**Comment by riley-badour** [comment]
Thats not right tablet that a t172 ????? Is it a wacom or a huion tablet your trying to get help with
I see the driver is picking up a huion one but i dont know what model it is.

Real question do you have more than one tablet conected to your pc

**Comment by Skopega** [comment]
I have the only tablet connectd to my pc right now. Its Wacom Bamboo MTE-450.

**Comment by hawku** [comment]
@riley-badour Did you download a wrong `startuplog.txt`?

**Comment by riley-badour** [comment]
#
# Huion H610P v2
#
USBTablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}"
CheckString 201 "HUION_T172"
Name "Huion H610P v2"
ReportId 0x02
ReportLength 8
DetectMask 0x90
IgnoreMask 0x60
MaxX 50800
MaxY 31750
MaxPressure 8191
Width 254
Height 158.75


if you have a h610 try this i don't know if it will work but its should

**Comment by riley-badour** [comment]
yes i did hawku

**Comment by hawku** [comment]
@Skopega Edit MTE-450 config in the `wacom.cfg`.
Change `DetectMask 0x00` to `DetectMask 0x10` and restart the driver.

**Comment by Skopega** [comment]
Yeah, thanks, it works!
