### ISSUE TITLE
Can I setting 300hz smoothing rate?

### ISSUE THREAD

**Issue by vipnight320** [hawku/TabletDriver#348]
I believe that 300hz rate setting is most needed to achieve the best performance.
Because I feel that it is necessary to set a rate between 333 hz and 250 hz long setting ;')

## Hardware/software information
Windows Version: 10

Tablet Driver version: v0.2.3

Tablet model: ctl-480

**Comment by hawku** [comment]
@vipnight320 Why do you think that 300Hz is the best?
250Hz means that the filter timer is running every 4 milliseconds and 333.333...Hz is 3 milliseconds.
Why would you want a timer that is running every 3.333... milliseconds (300 Hz)?
