### ISSUE TITLE
Windows Ink Button Remap

### ISSUE THREAD

**Issue by BobVonBob** [hawku/TabletDriver#356]
I'm not sure if this is a bug/not implemented in Tablet Driver or a limitation of Windows Ink, but in Windows Ink mode pen buttons are not remappable.

## Hardware/software information
Windows Version: Win 10 Pro Version 1809

Tablet Driver version: V0.2.3

Tablet model: XP-Pen G640

**Comment by hawku** [comment]
@BobVonBob Pen buttons are remappable in Windows Ink mode.
Can you post a video or a better explanation of the problem?

**Comment by BobVonBob** [comment]
My mistake, I wasn't clicking "Save settings" while testing this.
