### ISSUE TITLE
QUESTION: How to export area?

### ISSUE THREAD

**Issue by Scotxd** [hawku/TabletDriver#36]
Not an issue, but how do I export the area from my old wacom 5.3.5-3 drivers to these?

## Hardware/software information
Windows Version: win 10

Tablet Driver version: 0.0.13

Tablet model: ctl-471

**Comment by SuperTilted** [comment]
Don't think there's a way for exporting yet but you can just manually input the values of your old area yourself by clicking on the "Wacom Area" right under Rotation. A pop up will show up and allow you to input your values in the same format as a Wacom driver's. 

![wacomareabutton](https://user-images.githubusercontent.com/37356101/37487518-fde57b86-284e-11e8-9391-9698fc516296.png)

**Comment by hawku** [comment]
@Scotxd You could try this: https://github.com/SaltimusPrime/WacomAreaChanger/releases

I might add way to import Wacom backup file.
