### ISSUE TITLE
MSVCP140.dll and VCRUNTIME140.dll not found when I launch tablet driver

### ISSUE THREAD

**Issue by codly68** [hawku/TabletDriver#363]
Every time i launch the driver it just continuously pops up with those two errors. I have no idea what to do

## Hardware/software information
Windows Version: windows 10

Tablet Driver version: 0.2.3

Tablet model: wacom cth480

**Comment by riley-badour** [comment]
Please at least read the install instructions its even the first step https://github.com/hawku/TabletDriver/blob/master/README.md#installation

**Comment by codly68** [comment]
I did read the instructions, I had both things from the first step installed but redownloading one of them seems to have solved the problem

**Comment by riley-badour** [comment]
Restart your computer always helps

**Comment by codly68** [comment]
Well it seems to working now but Its giving the driver stopped restarting error.

**Comment by riley-badour** [comment]
You should try to install the vmuti drivers with admin and drop a startuplog.txt

**Comment by codly68** [comment]
Well all seems to be working just had to uninstall and reinstall the vmulti driver
