### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Valihack** [hawku/TabletDriver#369]
Could u tell me the command to execute a cfg usersettings, or maybe import export buttons

## Hardware/software information
Windows Version:  W10

Tablet Driver version: 0.2.3

Tablet model: XP-PEN DECO 01 v2

**Comment by hawku** [comment]
@Valihack You can use `Include` command to execute commands from a file.
There are already import and export buttons in the main menu.
https://github.com/hawku/TabletDriver/blob/d53eb54f16930ec76936295579f34043d8416f36/TabletDriverService/CommandHandler.Other.cpp#L640-L660
