### ISSUE TITLE
The driver is not working at all

### ISSUE THREAD

**Issue by Micnasr** [hawku/TabletDriver#385]
Windows Version: Windows 10 64 bit

Tablet Driver version:  0.2.3

Tablet model: Huion H420

It was working perfectly fine and then out of no where the next day it says: Huion H420 connected but its not working at all. My tablet is literally not picking up the driver and I dont know what to do.
![settings](https://user-images.githubusercontent.com/44876651/54056328-b9013800-41bd-11e9-8318-f11bfab17f9f.PNG)

**Comment by Exumk** [comment]
God, i have te same problem
