### ISSUE TITLE
Huion HS64 support?

### ISSUE THREAD

**Issue by nekoellie** [hawku/TabletDriver#403]
Just a simple question (I hope)
Will there be support for the Huion HS64? The outside looks exactly the same as the H430p, but I can't say the same about how it works. My tablet will arrive in two weeks so if anyone needs any data from it, tell me how I can provide you with such.

**Comment by InfinityGhost** [comment]
If it isn't already supported, support is quite easy to add for Huion tablets usually

**Comment by nekoellie** [comment]
tried and can see that the HS64 does not work with TabletDriver yet. TabletDriver does see it tho. could add console log later today when i'm home

**Comment by Jet-chann** [comment]
I'd like to see support on this tablet aswell.

**Comment by InfinityGhost** [comment]
@Jet-chann I would like to try to see what I can get working on your end. I worked with @nekoellie on this previously and got to the point it detected the tablet and all, but windows ink always took priority.
