### ISSUE TITLE
Can't start driver check console!

### ISSUE THREAD

**Issue by Gruee** [hawku/TabletDriver#407]
I have no idea why this is happening... My tablet isnt working with the driver and cant do anything with it. Also i cant save any of my layouts and stuff it says: Error occured while saving configuration. Please help me cuz i cant play osu :(

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: Intuos CTH 480
![problem](https://user-images.githubusercontent.com/49790883/56432392-6e4f0180-62cd-11e9-8a2a-fdca81b7b9b0.PNG)

**Comment by Gruee** [comment]
Bump

**Comment by InfinityGhost** [comment]
Well what does the console say

**Comment by Gruee** [comment]
ugh never mind im just dumb and extracted the program from the folder that seems to have caused the problem... A mod can close this thread since the issue has been resolved :)

**Comment by InfinityGhost** [comment]
(you can click close issue to do that yourself)
