### ISSUE TITLE
doesn't work on 32 bit?

### ISSUE THREAD

**Issue by Erannn** [hawku/TabletDriver#41]
https://i.imgur.com/SWhoH5L.png
Trying to install those drivers, wont work.
@hawku @kevinwlau please help me :(
## Hardware/software information
Windows Version: Windows 7 32-bit (dont kill me, i know its trash)

Tablet Driver version: trying to install

Tablet model: CTL-480 (Intuos P S)

**Comment by vietnam13231** [comment]
At the moment:
Supported operating systems:

    Windows 7 64-bit
    Windows 8 64-bit
    Windows 8.1 64-bit
    Windows 10 64-bit

So, no support for 32-bit systems as of now. No point in trying at this point of time. Maybe hawku will add support for them at some point...
