### ISSUE TITLE
Please update to support Gaomon S620

### ISSUE THREAD

**Issue by KarenAraragi** [hawku/TabletDriver#411]
I would love to use Hawku drivers for my Gaomon S620, but it doesn't seem that it is supported yet. Please look into this. <3 

## Hardware/software information
Windows Version: Windows 10 build 1809 

Tablet Driver version: Latest

Tablet model: Gaomon S620

**Comment by InfinityGhost** [comment]
https://github.com/hawku/TabletDriver/pull/412 adds support for this tablet.

**Comment by KarenAraragi** [comment]
@InfinityGhost Thank you!

**Comment by InfinityGhost** [comment]
[**Download this release here**](https://github.com/InfinityGhost/TabletDriver/releases/tag/v0.2.4-pre)
This is my private pre-release that includes the support for this tablet. This repository seems to have died and I want to keep it alive as long as possible, so I'll be improving on it over time.
