### ISSUE TITLE
CTL-490 feels like driver is being ignored

### ISSUE THREAD

**Issue by Kottowo** [hawku/TabletDriver#418]
So, i started my pc, wanting to play some osu, when i started it up, my tablet area was reset to full tablet area. Windows ink popped up, disabled it but it didn't affect anything. When i close the driver however, the tablet still works. I've tried disabling the wacom drivers (which i didn't install since this was a new pc and didn't need to since this driver exists), the huion drivers (just to make sure, even tho i use wacom), uninstalled and re installed the Vmulti drivers and messing with the settings in the driver itself. When i messed with the settings, nothing changed so i have a feeling something else is denying the tablet driver and it's using that instead. Hopefully someone can help...

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.2.3

Tablet model: CTL-490

**Comment by InfinityGhost** [comment]
Seems as if another driver was installed for the tablet, most likely a generic windows 10 driver. Try checking in device manager for the tablet and then uninstall the driver then try running TabletDriver again without restarting

**Comment by Kottowo** [comment]
when i tried that, it gave me an error that it could not find the tablet

**Comment by Kottowo** [comment]
when i re plugged it in, it works again, but it's the same issue. The thing that I am getting is that it says this (look at the screenshot below) but i have tried uninstalling the wacom drivers multiple times 
![unknown](https://user-images.githubusercontent.com/50766751/57973350-e5001d00-79a7-11e9-99f7-fc372296f9e3.png)

**Comment by InfinityGhost** [comment]
Do they stay on your system after uninstalling? Make sure the Wacom tablet service isn't running in `services.msc`

**Comment by Kottowo** [comment]
wacom professional services is running

**Comment by Kottowo** [comment]
i stopped it, restarted the driver but it still says the same thing (like in the screen above)

**Comment by Kottowo** [comment]
even when i just restarted my pc, it immediately works (without drivers)

**Comment by Kottowo** [comment]
![image](https://user-images.githubusercontent.com/50766751/57973458-4c6a9c80-79a9-11e9-9c95-ddb16c7cda16.png)
should i try uninstalling the wacom tablet from my installed programs?

**Comment by Kottowo** [comment]
well, that was the whole issue, me not deleting the "wacom tablet"
still ty for the effort you gave in the hopes of fixing this
