### ISSUE TITLE
Driver stopped. Restarting

### ISSUE THREAD

**Issue by quitwlol** [hawku/TabletDriver#423]
I still haven't figured out what the problem is with my tablet. I keep redownloading and everything but nothing still works. I need to use my tablet. Please solutions. 
Tablet model: Huion H420

**Comment by InfinityGhost** [comment]
Send the `startuplog.txt` file

**Comment by quitwlol** [comment]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/3221150/startuplog.txt)

**Comment by InfinityGhost** [comment]
Make a backup of your `\config` folder, then extract [config.zip](https://github.com/hawku/TabletDriver/files/3221513/config.zip) into the `\config` folder, overwriting files if asked. Send the `startuplog.txt` file again if it fails.

**Comment by quitwlol** [comment]
holy poggers! thanks!
