### ISSUE TITLE
support for xp pen drivers (star 03) 

### ISSUE THREAD

**Issue by Saxarokkkk** [hawku/TabletDriver#430]
## Hardware/software information
Windows Version: win 10 pro 

Tablet Driver version: latest

Tablet model: xp pen star 03

**Comment by Akiz09** [comment]
#
# XP-Pen Star 03 
#
HIDTablet 0x5543 0x0081 0xFF0A 0x0001
Name "XP-Pen Star 03"
ReportLength 8
DetectMask 0x80
MaxX 20320 //not shure
MaxY 15240 //not shure
MaxPressure 2047
Width 101.6 //not shure
Height 76.2 //not shure
InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00

**Comment by TakejiReydzey** [comment]
> # XP-Pen Star 03
> HIDTablet 0x5543 0x0081 0xFF0A 0x0001
> Name "XP-Pen Star 03"
> ReportLength 8
> DetectMask 0x80
> MaxX 20320 //not shure
> MaxY 15240 //not shure
> MaxPressure 2047
> Width 101.6 //not shure
> Height 76.2 //not shure
> InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00

doesn't work for me tho
