### ISSUE TITLE
ERR0R api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by Frijolera** [hawku/TabletDriver#45]
Error api-ms-win-crt-runtime-l1-1-0.dll.
in the last days that I started the drivers they were fine, but today I get this error.
already try reinstalling the drivers but it still does not work help pls.
https://imgur.com/a/QcVIl

## Hardware/software information
Windows Version: Windows 8.1

Tablet Driver version: 0.0.17

Tablet model: Wacom Ctl-480

**Comment by hawku** [comment]
I think that you are missing this Windows update:
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
