### ISSUE TITLE
[Not Important] Disable auto restart

### ISSUE THREAD

**Issue by HilmTien** [hawku/TabletDriver#454]
Ok, so this isnt very important but every time my tablet is unplugged, my cursor teleports to the top left corner on osu every time the driver restarts. My temporary solution to this was closing the driver, but I would like a feature where you can turn off the auto restart and just use the restart driver button when you want to use it! 

## Hardware/software information
Windows Version: 1803

Tablet Driver version: 0.2.3

Tablet model: CTH-480

**Comment by YChvanov** [comment]
Cursor teleport is a known thing for a long time and since 0.2.1 auto restart can be disabled in bottom right corner

**Comment by HilmTien** [comment]
Im blind. ahahha well thanks anyways!
