### ISSUE TITLE
Can't open VMulti Device!

### ISSUE THREAD

**Issue by sutoraiku** [hawku/TabletDriver#459]
installing vmulti driver:
![image](https://user-images.githubusercontent.com/54072006/62950586-b7681b80-bdbe-11e9-8fc3-c5ac56a07324.png)
![image](https://user-images.githubusercontent.com/54072006/62950673-e3839c80-bdbe-11e9-8a1f-3c3e36971c7d.png)

## Hardware/software information
Windows Version: win10

Tablet Driver version: devocub 1.5.5

Tablet model: ctl-671
pls, someone help me

**Comment by nkiefer12** [comment]
did you fix the issue, because I have the same one and can't find a way to fix it

**Comment by sutoraiku** [comment]
i  fixed upgrading all drivers in my pc at least version

Em seg., 20 de abr. de 2020 às 12:53, nkiefer12 <notifications@github.com>
escreveu:
