### ISSUE TITLE
Some solution for my desire.

### ISSUE THREAD

**Issue by mmnt1337** [hawku/TabletDriver#464]
I want the cursor to stop moving when I raised the pen, but I don’t have enough skill to come up with something or code myself.
thank you in advance

**Comment by InfinityGhost** [comment]
That's not a bad idea at all. I'll figure out something on my fork eventually.

**Comment by hawku** [comment]
@mmnt1337 For the relative mouse mode there is a feature like that.
Change mode to "Relative (Mouse)" and add `RelativeDragMove 1` to commands tab.
After that the cursor will only move if a pen pressure is detected.

@InfinityGhost 
https://github.com/hawku/TabletDriver/blob/d53eb54f16930ec76936295579f34043d8416f36/TabletDriverService/CommandHandler.Tablet.cpp#L725-L737

https://github.com/hawku/TabletDriver/blob/d53eb54f16930ec76936295579f34043d8416f36/TabletDriverService/OutputManager.cpp#L117-L121

**Comment by mmnt1337** [comment]
> @mmnt1337 For the relative mouse mode there is a feature like that.
> Change mode to "Relative (Mouse)" and add `RelativeDragMove 1` to commands tab.
> After that the cursor will only move if a pen pressure is detected.

dosen't work on xp-pen g430 (v.0.2.3)
Cursor move when pen 2-3 cm away from tablet like it is would be before

**Comment by mmnt1337** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/53450571/63269256-8005dd00-c29e-11e9-8bc4-131aae4d286b.png)
![Screenshot_5](https://user-images.githubusercontent.com/53450571/63269257-809e7380-c29e-11e9-8609-186af3f81e1a.png)
Maybe something wrong?

**Comment by hawku** [comment]
@mmnt1337 Sorry, I didn't remember that 0.2.3 doesn't have that feature.
Use InfinityGhost's version of TabletDriver: https://github.com/InfinityGhost/TabletDriver/releases/download/v0.2.4-pre/TabletDriverGUI.Release.zip

**Comment by mmnt1337** [comment]
@hawku Oh,thank u very much
