### ISSUE TITLE
[ERROR] Tablet init failed! (Cant find CTL-480 ?

### ISSUE THREAD

**Issue by marcoboy123** [hawku/TabletDriver#48]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/1822874/startuplog.txt)

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: v.0.0.18 

Tablet model: CTL-480 Wacom

Yeah yeah you can see all my USB devices plugged in.. and idc :P

**Comment by hawku** [comment]
Check the issue #1

**Comment by marcoboy123** [comment]
So basically, update Windows 10 ?

**Comment by hawku** [comment]
Yes, you only need to install the vmulti driver.
