### ISSUE TITLE
Problem with TabletDriverService.exe

### ISSUE THREAD

**Issue by Cheetek** [hawku/TabletDriver#497]
I have a problem with turning on the last TabletDriver because I recently wanted to play osu!, And here suddenly he writes me something like this:
![Screenshot_17](https://user-images.githubusercontent.com/55852265/65713311-35dffa80-e099-11e9-9299-faed5e29e85f.png)

 I don't know what it is, but when I tried to turn it off by Task Manager, he writes to me: ![Screenshot_18](https://user-images.githubusercontent.com/55852265/65713336-43958000-e099-11e9-8567-a9499a2e91ff.png) Please help.

**Comment by Cheetek** [comment]
Oh, and Hardware/software information
Windows Version: 10 (home)

Tablet Driver version: Latest 

Tablet model: XP-Pen G430S

**Comment by jjhhgg100123** [comment]
Use [Infinity ghost's](https://github.com/InfinityGhost/TabletDriver) fork instead.

**Comment by Cheetek** [comment]
Yes i tried kill that process tab but I see text: The operation could not be completed. Acces is denided.

When i downloaded that Infinity ghost's fork instead, them I have that error: 
![image](https://user-images.githubusercontent.com/55852265/65786301-a731b300-e156-11e9-8443-45cab019aa0e.png)

**Comment by Cheetek** [comment]
And when I tried close this app with command propot, them I have that: 
![image](https://user-images.githubusercontent.com/55852265/65786545-23c49180-e157-11e9-9de4-60b4edd779fa.png)

**Comment by jjhhgg100123** [comment]
Did you right click and run the command prompt as an admin?

Try deleting the folder normally, or with the command prompt.

**Comment by Cheetek** [comment]
Ye I tried delete a folder, but that proccess is nonstop active. When I opened command prompt as an admin, and when I type that command, then I saw that: 
![image](https://user-images.githubusercontent.com/55852265/65816691-5f1a9b00-e1ff-11e9-81bf-8fd9ae9bbf8d.png)

**Comment by Cheetek** [comment]
And when I type that command I saw that: 
![image](https://user-images.githubusercontent.com/55852265/65816737-b7519d00-e1ff-11e9-9c5d-4d34d0e6142d.png)

**Comment by Cheetek** [comment]
![image](https://user-images.githubusercontent.com/55852265/65816765-00a1ec80-e200-11e9-9475-eb1da5d66411.png)

**Comment by jjhhgg100123** [comment]
Boot in to safe mode and delete the folder.

**Comment by InfinityGhost** [comment]
There's some permission issue here for sure, I would definitely follow this:

> Boot in to safe mode and delete the folder.

**Comment by InfinityGhost** [comment]
Something is starting the process without your permission, which is likely corrupted and/or has been compromised

**Comment by Cheetek** [comment]
Ye, when I start my pc, them I saw that: 
![image](https://user-images.githubusercontent.com/55852265/65832303-0b24ba80-e2c2-11e9-99c0-ce9bb3477183.png)

**Comment by InfinityGhost** [comment]
Have you deleted that executable in safe mode?

**Comment by Cheetek** [comment]
But how can I delete him in safe mode?

**Comment by InfinityGhost** [comment]
Boot into safe mode and all startup applications will be disabled no matter what. This will allow you to delete the file itself and it won't open on startup anymore

**Comment by Cheetek** [comment]
Ok, but how can I boot into safe mode?

**Comment by InfinityGhost** [comment]
![image](https://user-images.githubusercontent.com/39218853/65836573-5ee1d480-e2bf-11e9-884d-2851e5739965.png)
Open settings, Update and Security, Recovery

**Comment by Cheetek** [comment]
Ok, and when I boot my pc to safe mode, then what?

**Comment by InfinityGhost** [comment]
Delete the tabletdriverservice.exe that was running

**Comment by Cheetek** [comment]
Ok i deleted. What now?

**Comment by Cheetek** [comment]
Omg that worked, but now I'm need that TabletDriverService: 
![image](https://user-images.githubusercontent.com/55852265/65837129-37f1c580-e2f4-11e9-870b-9cb9e9f8a250.png)

**Comment by Cheetek** [comment]
Ok, i'm reinstalled that driver, but now I have that error: 
![image](https://user-images.githubusercontent.com/55852265/65837189-a59df180-e2f4-11e9-8722-011981d18d51.png)

**Comment by Cheetek** [comment]
Ok i'm started the driver with administrator. Im closing that.
