### ISSUE TITLE
Can run multiple instances of the driver

### ISSUE THREAD

**Issue by Zinkton** [hawku/TabletDriver#5]
If you launch a 2nd instance and change the area on it, both area from instance 1 and area from instance 2 will be active and you'll have 2 cursors. May be fixed by just maximizing the current instance when trying launch the program?

**Comment by Shoko84** [comment]
Requested a commit about that issue, can be merged into the master branch if it hasn't already been done locally from @hawku 's side 👍

**Comment by hawku** [comment]
@Shoko84 thanks for the pull request!
I had a different solution for the problem, but I really appreciate any pull request for this project!

**Comment by Shoko84** [comment]
I would be glad to help you and to contact you anytime if you have some few spare issues (well idk where we could be anyways :D)
