### ISSUE TITLE
driver stopped. restarting!! check console!!

### ISSUE THREAD

**Issue by rubberdoe** [hawku/TabletDriver#504]
this started happening 4 days ago and I'm not sure whats wrong, I tried using it on different computers and it still didn't work. also gives me "[ERROR] Tablet not found!" even though its connected. please help

## Hardware/software information
Windows Version: 10

Tablet Driver version: TabletDriverV0.1.5.5.Devocub.Edition

Tablet model: CTH-480

**Comment by InfinityGhost** [comment]
Try a newer version of TabletDriver, and see if the problem persists.

**Comment by rubberdoe** [comment]
> Try a newer version of TabletDriver, and see if the problem persists.

already tried this, did not work sadly.

**Comment by InfinityGhost** [comment]
The only reason I could see this happening is that the `config` directory doesn't contain `wacom.cfg` with the CTH-480 configuration.

**Comment by rubberdoe** [comment]
alright so yesterday i figured out what the problem was. I just needed a new wire LOL, thanks for the help though :D
