### ISSUE TITLE
CTL-480 [ERROR] Tablet not found! 

### ISSUE THREAD

**Issue by Alphaheat** [hawku/TabletDriver#521]
Always running into the error saying that my tablet is not found. I've removed all Wacom drivers from Device Manager and looked into control panel's "Uninstall a program" for anything related to Wacom (couldn't find anything relating to any tablets let alone Wacom). I also re-downloaded the Wacom driver for my specific tablet to remove it again and the problem persists. I have removed the vmulti driver and reinstalled it every step that I mentioned above as well. 

Also I would like to add that I also ran TabletDriverGUI as admin. Additionally I can also find Wacom's HID device instance path in Windows Device Manager. It shows up as HID\VID_056A when my tablet is plugged in. 

Update: For some reason the dev build works for me... Not sure if that version is any better than the current one. Here's the link for the download: https://github.com/hawku/TabletDriver/issues/355#issuecomment-458611540

## Hardware/software information
Windows Version: Windows 10 Ver. 10.0.18362 Build 18362

Tablet Driver version: 0.2.3

Tablet model: CTL-480

**Comment by Alphaheat** [comment]
Found a fix for it. The .cfg files in the config folder were busted for some reason. Re-downloaded the TabletDriver zip folder again and ran it wthout any issues. Problem has now been solved.

**Comment by asd694427704** [comment]
I have the same problem as you, can you teach me how to solve it?
