### ISSUE TITLE
Cannot install Vmulti

### ISSUE THREAD

**Issue by Elaborateshoe** [hawku/TabletDriver#527]
![image](https://user-images.githubusercontent.com/57603074/68551297-6e356100-03d9-11ea-9b0f-3d4ac2036b0f.png)

I cannot install Vmulti even though I have run it as an admin, removed vmulti as admin, and made sure all Wacom drivers are not installed. Any help is appreciated

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: Wacom CTH-470

**Comment by allbombson** [comment]
I see u have a Bamboo CTH-470, same as me. What version of Wacom drivers did u have installed before?

**Comment by Elaborateshoe** [comment]
>I have 
Driver 5.3.5-3 (Windows XP, Vista, Win 7, 8, & 10)

38.2 MB 8/20/2015

**Comment by Elaborateshoe** [comment]
> 
> 
> I see u have a Bamboo CTH-470, same as me. What version of Wacom drivers did u have installed before?

I have Driver 5.3.5-3 (Windows XP, Vista, Win 7, 8, & 10)

38.2 MB 8/20/2015
