### ISSUE TITLE
Getting Tablet init failed

### ISSUE THREAD

**Issue by Dynamicrhino1** [hawku/TabletDriver#53]
My TabletGUI keeps telling me that the Driver has stopped and tries to restart but the tablet init fails, i've tried to reinstall my drivers already but to no avail.

https://cdn.discordapp.com/attachments/376062244523474964/425406328023023618/unknown.png

## Hardware/software information
Windows Version: Windows 10 Home

Tablet Driver version: 6.3.29-4

Tablet model: CTH-480

**Comment by hawku** [comment]
Check the issue #1

**Comment by Dynamicrhino1** [comment]
I see, thank you got it fixed now.
