### ISSUE TITLE
system error driver wont run

### ISSUE THREAD

**Issue by aaaaaaaaahhhhhhh** [hawku/TabletDriver#537]
if I try to run I get a system error: MSVCP140.dll not found and VCRUNTIME140.dll was not found. I've uninstalled and reinstalled the driver, I did a system check and everything was fine, I'm
 not sure what's wrong, I haven't downloaded anything or changed anything.

## Hardware/software information
Windows Version: 
windows 10 version 1909
Tablet Driver version: 
V0.2.3
Tablet model: 
wacom ctl-490

![msv](https://user-images.githubusercontent.com/58139162/69495503-8e781c00-0ebf-11ea-9086-960278836e12.png)
![vcrunt](https://user-images.githubusercontent.com/58139162/69495504-8e781c00-0ebf-11ea-9f0e-567d4fadef24.png)

**Comment by InfinityGhost** [comment]
Follow installation instructions thoroughly.

**Comment by aaaaaaaaahhhhhhh** [comment]
> Follow installation instructions thoroughly.

I have multiple times. I didn't change anything when the driver stopped working, so it was installed properly before the error occurred

**Comment by euphoricals** [comment]
I'm getting the same issue, and I've followed all of the instructions multiple times.

**Comment by InfinityGhost** [comment]
Install both
- https://www.microsoft.com/net/download/dotnet-framework-runtime
- https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by euphoricals** [comment]
That worked for me, thanks so much

**Comment by aaaaaaaaahhhhhhh** [comment]
> Install both
> 
> * https://www.microsoft.com/net/download/dotnet-framework-runtime
> * https://aka.ms/vs/15/release/vc_redist.x86.exe

it worked, thank you. I already repaired my C++ but your link work for some reason
