### ISSUE TITLE
Cursor stuck on left side of screen, tried searching issue here none of the solutions worked. Veikk s640

### ISSUE THREAD

**Issue by Ellenoria** [hawku/TabletDriver#552]
This started happening about a week ago.
While playing osu, tablet stopped working correctly, restarted driver and it failed saying that the vmulti was missing. Uninstalled and reinstalled Vmulti_64.
Since then the cursor has been stuck on the left side whenever I try to select osu as the window. Selecting anything else and changing the active region of the tablet is very unstable and the cursor lags behind.
I've deleted the whole zip, uninstalled the drivers, then reinstalled everything and that didn't work. 
I've tried disabling raw input for osu and that works for about 10 seconds before snapping to the left side of the screen again. 
There's no option on the hawku driver to disable windows ink and it won't let me disable it from regedit either, I tried disabling it from there as well. 
I don't have pentabletservice.exe. I do have tabletinputservice but that will not let me stop or restart.

Also I have to have the tabletdriver.exe open on my desktop or the tablet will not work, it no longer minimizes to tray.

I'd like to know if there's something I'm not seeing that I'm doing incorrectly. The vmulti driver should be the only driver installed. 
Any other driver makes osu unplayable because it lags just enough for me to not be able to play, so I'd really appreciate if someone could look over this. 

These are the settings that I was working with earlier and they were working fine up until the issue.

![Capture](https://user-images.githubusercontent.com/59038123/71139209-232a1d00-21d3-11ea-92e4-b0e2cb80f679.PNG)

Some console logs

![image](https://user-images.githubusercontent.com/59038123/71139550-178b2600-21d4-11ea-90fa-b5b2328054a4.png)

![image](https://user-images.githubusercontent.com/59038123/71139605-3f7a8980-21d4-11ea-9f5b-ce7e354d5a1f.png)

![image](https://user-images.githubusercontent.com/59038123/71139695-85cfe880-21d4-11ea-9265-8f49403571e8.png)

## Hardware/software information
Windows Version: windows 10 home latest update

Tablet Driver version: 0.2.3

Tablet model: veikk s640

**Comment by Ellenoria** [comment]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/3995767/startuplog.txt)

Since posting I've also tried installing and uninstalling wacom drivers, installing a previous version of this driver, and changing the configs detect mask.

I have a temporary fix by disabling my second monitor and restarting my computer, but I'd really not like to restart my computer and have a single monitor whenever I feel like playing the game.

**Comment by Ellenoria** [comment]
I've found the main issue.
When setting it to the osu window the driver isn't recognizing that it's on the screen anymore since it's minimized, on previous versions of windows it still pulled the window (still showed the same offset on the driver gui which is why I wasn't sure what was going on)
In game you have to temporarily set the cursor to never be confined to the screen, then change the tablet to the osu window and it will work like it did before.
This issue was driving me insane for weeks so hopefully this solution helps someone else.

**Comment by youi645** [comment]
Can you explain more on how to fix it Im confused.

**Comment by youi645** [comment]
ity didnt hewlp :)))()((((

**Comment by Ellenoria** [comment]
This is almost a two year old post. Most likely your solution isnt here and you’ll have to make a new one.
