### ISSUE TITLE
xp pen g430s stutter lag problem 

### ISSUE THREAD

**Issue by comm899** [hawku/TabletDriver#556]
the problem of xp-pen g430s is that the cursor disappear when I moving.Moreover,in game osu using it the stutter lag is terrible.When I use xp pen driver it doesn't have any problem of it.How about hawku can solve this problem?

## Hardware/software information
Windows Version: 1903

Tablet Driver version: 0.2.3

Tablet model: xp pen g430s

**Comment by NiceGoodRU** [comment]
I have the same problems =(
