### ISSUE TITLE
"save settings" button has issue

### ISSUE THREAD

**Issue by aDelightz** [hawku/TabletDriver#576]
![image](https://user-images.githubusercontent.com/48697287/73040238-f1c8ff00-3eac-11ea-8ae1-ae7f1ace14b2.png)
idk how to give it perms for editing file directory
this means id have to export and import settings manually through these options 
![image](https://user-images.githubusercontent.com/48697287/73040382-8cc1d900-3ead-11ea-9cd1-4c36d486df84.png)
 every time and select the files in /documents but by then it would be quicker to just do the settings again

## Hardware/software information
Windows Version: Windows 10, version 1909

Tablet Driver version: TabletDriverV0.2.3

Tablet model: VEIKK S640

**Comment by aDelightz** [comment]
fixed by reinstalling: startuplog text file created automatically this time

**Comment by aDelightz** [comment]
fixed by putting it in a separate folder

**Comment by Jeromvjr** [comment]
wait how did you exactly fix it, I have the same problem

**Comment by aDelightz** [comment]
i originally put it in E:\Program Files folder which the app doesn't have the permissions to change files in, so I moved it from the program files folder straight to the ssd E:\ as its own folder (if you are putting it on your main harddrive/ssd for you it will probably be C:\)
moving the tablet drivers folder to documents or desktop or whatever would probably work as well so long as when you try to click save settings it doesn't pop up with a message saying it cannot create and edit files there.

sorry for the late response xd

**Comment by billskii** [comment]
I have the same problem

**Comment by slikaa** [comment]
same i need help

**Comment by MMenyan** [comment]
oops i never closed this
