### ISSUE TITLE
Screen mapping with different monitor sizes

### ISSUE THREAD

**Issue by Master-chan** [hawku/TabletDriver#6]
I have 2 displays with different sizes and it seems that driver is unable to pick up 2nd monitor at all. Win7.
![explorer_2018-03-13_17-17-38](https://user-images.githubusercontent.com/1059861/37341253-92ea51ca-26e2-11e8-90c1-839f34c0b7d0.png)
![tabletdrivergui_2018-03-13_17-18-04](https://user-images.githubusercontent.com/1059861/37341260-96486f50-26e2-11e8-845c-ffc0704c339b.png)

**Comment by hawku** [comment]
https://github.com/hawku/TabletDriver/issues/4

**Comment by hawku** [comment]
Windows 7 doesn't support absolute mouse positioning with vmulti driver. Only main display is supported.

**Comment by Master-chan** [comment]
That is unfortunate.
