### ISSUE TITLE
CTL-471 tablet area issue.

### ISSUE THREAD

**Issue by RewiB** [hawku/TabletDriver#60]
The area is really small and I can't make it bigger. It's almost halved, even if "Full Area" checkbox is set.
https://imgur.com/a/50Rrg

## Hardware/software information
Windows Version: 10 

Tablet Driver version: 0.1.0

Tablet model: CTL-471

**Comment by hawku** [comment]
@RewiB It looks like a number conversion problem.
Try the latest version. I've modified the number conversion code.

**Comment by RewiB** [comment]
@hawku Works now. Thanks.
