### ISSUE TITLE
0xc000007b error reinstalled .net and c++

### ISSUE THREAD

**Issue by BlueToffe** [hawku/TabletDriver#611]
i have downloaded the c++ and net and it still shows the error

Windows Version: win 10

Tablet Driver version: 0.2.3

Tablet model: G640

**Comment by IAmDuDa** [comment]
Are you sure you did this instalation step:

"
You might need to install these libraries, but usually these are already installed:

    https://www.microsoft.com/net/download/dotnet-framework-runtime
    https://aka.ms/vs/15/release/vc_redist.x86.exe
"

I was having the same issue because I didn't do this

**Comment by BlueToffe** [comment]
yes i have

**Comment by BlueToffe** [comment]
i figured it out i just had to reinstall windows
