### ISSUE TITLE
"Can't open VMulti Device!"

### ISSUE THREAD

**Issue by Ducknorriss** [hawku/TabletDriver#615]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: (irrelevant) XPpen g640s

When I open the driver and check the console it says that the bin file cannot be found:

![hawkudrivererror1](https://user-images.githubusercontent.com/63251330/78579021-56ce9880-77fe-11ea-9518-bc3e82e31fd6.png)

Because of this, I go to open the bin file, and when I do, this pops up for a quick second before closing:
![hawkudrivererror2](https://user-images.githubusercontent.com/63251330/78579039-5b934c80-77fe-11ea-9142-c5d4958d133c.png)

When I open the bin file again, after downloading vmulti driver, I get the same error. I would like to add that I just got the laptop that I am using a week ago and have not downloaded any other drivers, so that has no interference. Anyone have any suggestions?

**Comment by inevail** [comment]
exact same w me, have you figured out the issue?

**Comment by Ducknorriss** [comment]
No, I have not. I will probably just try using different drivers.

**Comment by inevail** [comment]
I found a fix. There should be a folder automatically on your desktop with all of the contents of the hawku driver. You have to use the TabletHub specifically from that folder.

**Comment by inevail** [comment]
if there isn’t, create a whole new folder on your desktop and extract all contents of the hawku driver into it.

**Comment by Ducknorriss** [comment]
what exactly do you mean by "TabletHub". I could not find a file by that or a similar name.

**Comment by inevail** [comment]
Do you have discord? if so add me inevail#4935, i’ll be able to help you out
