### ISSUE TITLE
"Driver stopped. Restarting! Check console !!!" (Huion 420)

### ISSUE THREAD

**Issue by temporaryrage** [hawku/TabletDriver#63]
Every time I would install huion_64 the tablet stops working. If I don't install it, it would say "Driver stopped. Restarting! Check console !!!". Help?

## Hardware/software information
Windows Version: 10

Tablet Driver version: Latest

Tablet model: Huion 420

**Comment by vietnam13231** [comment]
Are you sure you deleted previous drivers? If yes, delete folders left by stock driver (configuration backups can stay, you can use them in this driver), install this driver, restart your PC. If it still doesn't work, then I'm lost...

**Comment by Gerodar** [comment]
I have the same problem and I checked that I uninstalled every possible driver that I had. Program keeps saying "Driver stopped. Restarting! Check console !!!" and all listed fixes don't work.

Running on Win10 with latest drivers on a CTL-471

**Comment by hawku** [comment]
@temporaryrage Upload the startuplog.txt to here.

@Gerodar Check the issue #1
