### ISSUE TITLE
Huion H540

### ISSUE THREAD

**Issue by ShinyMyu** [hawku/TabletDriver#64]
I got bored and started messing around and I can get the gui to see my H540, but I cannot get any response from it. 

Here is the startup log: [startuplog.txt](https://github.com/hawku/TabletDriver/files/1835876/startuplog.txt)

and here is what I've jankly throw together to at least let the gui see the tablet: 
```
#
# Huion H540
#
Tablet 0x256c 0x006e 0x0001 0x0080
Tablet 0x256c 0x006e 0x000c 0x0001
Name "Huion H540"
ReportLength 8
ButtonMask 0x00
MaxX 8340
MaxY 4680
MaxPressure 2047
Width 139.7
Height 101.6
```

Its really freaking jank, I think I based the code off the H420. 

I've tried a ton of different buttonmask combos, but none have gotten any response. 

Lemme know what else is needed to help troubleshoot. 

## Hardware/software information
Windows Version:  Win10 Pro 64

Tablet Driver version:  0.1.0

Tablet model:  Huion H540

**Comment by hawku** [comment]
You could try this:

```
Tablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}" 201 HVAN
Name "Huion H540"
ReportLength 8
DetectMask 0x80
MaxX 8340
MaxY 4680
MaxPressure 2047
Width 139.7
Height 101.6
```
