### ISSUE TITLE
Can't start driver!  bin/TabletDriverService.exe not found!

### ISSUE THREAD

**Issue by JustNothingHere** [hawku/TabletDriver#661]
So I'm new to this tablet driver and a new owner of this tablet and use it for osu! but when I try to open the tablet driver it says can't start driver check console! so I do but it says bin/Tablet DriverService.exe not found! even tough I use the tools to download vmulti drivers and to disable wacom services so if you can fix this thx!

## Hardware/software information
Windows Version:  windows 10 2004  19041.264

Tablet Driver version: V0.2.3

Tablet model: CTL4100

**Comment by JustNothingHere** [comment]
Actually never mind  I fixed the problem

**Comment by hopixs** [comment]
> Actually never mind I fixed the problem

how did you solve it?(
