### ISSUE TITLE
wacom ctl-460

### ISSUE THREAD

**Issue by popiwave** [hawku/TabletDriver#67]
Hello, I was wondering whether the driver works with the wacom ctl-460 or not. If anyone made it work and can send me the config I would very much appreciate it. Thanks!

## Hardware/software information
Windows Version: 

Tablet Driver version: 

Tablet model:

**Comment by hawku** [comment]
Wacom CTL-460 might work out of the box, but if it doesn't:
https://www.reddit.com/r/osugame/comments/83hbiq/testing_different_tablet_drivers_with_a_3d_printer/dvkwo2v/
