### ISSUE TITLE
Tablet not detected by driver. (G640)

### ISSUE THREAD

**Issue by MrWawas** [hawku/TabletDriver#671]
I've uninstalled and reinstalled the OEM drivers, and this driver 10+ times at this point, to no avail.
It always comes up with the same message, "Driver stopped. Restarting! Check console !!!" with the console saying "Tablet not found! Check the list of supported tablets."

I've also tried uninstalling the drivers, and device, from Device Manager. All with restarting my computer between installs/uninstalls.

Any help is appreciated, thanks in advance! :)

Start up log attached below;

[startuplog.txt](https://github.com/hawku/TabletDriver/files/4725685/startuplog.txt)

## Hardware/software information
Windows Version: Windows 10, 1909

Tablet Driver version: 0.2.3

Tablet model: XP-Pen Star G640

**Comment by ILikeNoodles0** [comment]
I have the same problem and same console message :(

**Comment by Baha290** [comment]
@MrWawas I have the same problem

**Comment by WonderfulDay0** [comment]
same problem

**Comment by ssccoonniicc** [comment]
You may have the second revision of the G640.
Check: https://www.reddit.com/r/osugame/comments/gwnrpv/important_xp_pen_released_a_new_g640/

**Comment by Baha290** [comment]
@ssccoonniicc it worked thank you.

**Comment by MrWawas** [comment]
> You may have the second revision of the G640.
> Check: https://www.reddit.com/r/osugame/comments/gwnrpv/important_xp_pen_released_a_new_g640/

For anybody else having the issue; make sure to check @ssccoonniicc's link and try that config.
