### ISSUE TITLE
TabletDriverGUI doesnt open

### ISSUE THREAD

**Issue by NorthGalaxy** [hawku/TabletDriver#676]
It worked but it doesnt anymore, the exe file opens but instantly says  "TabletDriverGUI has stopped working"

## Hardware/software information
Windows Version: Windows 7 Ultimate

Tablet Driver version: 0.2.3

Tablet model: wacom one ctl 672

**Comment by NorthGalaxy** [comment]
it worked on windows 10*

**Comment by Vlothx** [comment]
Install all updates available for your system. Common problem with Windows 7, that's why I don't recommend it anymore.

**Comment by NorthGalaxy** [comment]
> Install all updates available for your system. Common problem with Windows 7, that's why I don't recommend it anymore.

any specific updates to install?

**Comment by Vlothx** [comment]
All of them, should be like 6GB of updates (if you haven't updated your system).

**Comment by NorthGalaxy** [comment]
Fixed it by install vcredist 86 bit
