### ISSUE TITLE
drivers not working with XP pen 6430s

### ISSUE THREAD

**Issue by awesome1223** [hawku/TabletDriver#681]
basically, I've been using the g430s for a while now. I needed a new one due to scratches on my old tablet, I ordered a new one (the exact same tablet), but for some reason it wont work with the drivers. It doesn't pick up the tablet,,, but it still picks up my old one. I tried all the fixes I could find on here/reddit but nothing has worked so far,

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: XP-Pen g430s
[startuplog.txt](https://github.com/hawku/TabletDriver/files/4762006/startuplog.txt)

**Comment by Vlothx** [comment]
That's because, you might have a new revision. You can try with InfinityGhost's fork of TabletDriver (link [here](https://github.com/InfinityGhost/TabletDriver)). If you can't get it work, you can join the OpenTabletDriver discord and we might be able to help you with your problem.

**Comment by awesome1223** [comment]
holy shit it worked, thank you so much!!!!
