### ISSUE TITLE
Huion H420 only 130 reports per second

### ISSUE THREAD

**Issue by VulcanHestan** [hawku/TabletDriver#683]
## Hardware/software information
Windows Version: 2004

Tablet Driver version: 0.2.3

Tablet model: H420

With default drivers from huion it get the advertised 200hz polling. Where as with these drivers i get a lower polling than my fps to it looks like it is skipping frames. Is there a way to set the reports/polling or is this to be expected

**Comment by Vlothx** [comment]
> That happens because there's a problem with the CreateTimerQueueTimer WinApi function call. The only solution is, waiting until Microsoft officially fixes this.
> 
> Well, if you have a powerful enough computer, [you can use this fork.](https://github.com/AbdShullah/TabletDriver)
