### ISSUE TITLE
Running these drivers with Wacom drivers still installed onto the system

### ISSUE THREAD

**Issue by Yumi08** [hawku/TabletDriver#70]
## Hardware/software information
Windows Version: Version	10.0.16299 Build 16299

Tablet Driver version: V0.0.18

Tablet model: CTL-480

Sorry to bother, I know this isn't much to do with a bug. I just really need help on running this driver when I play Osu, and having my Wacom drivers so I can use my screen tablet. And it's really not an option to uninstall my Wacom drivers, because the screen tablet does nothing without them.

I've tried stopping all the Wacom services (or at least I think all of them), but it kept saying "Driver stopped. Restarting! Check console !!!" And in console it recommended for me to either uninstall or stop any other drivers, which I thought I did. So I'm really in a pickle here, and if anyone has any tips or a solution, please please tell me!

**Comment by hawku** [comment]
@Yumi08 I've added support for Wacom drivers in the latest version v0.1.2
Use `tools\disable_wacom_drivers.bat` and `tools\enable_wacom_drivers.bat` when switching between the drivers.

**Comment by Yumi08** [comment]
Thank you. It works perfectly fine as of what I've seen so far.
