### ISSUE TITLE
Cmd opened when i turned on pc

### ISSUE THREAD

**Issue by Axellious** [hawku/TabletDriver#71]
when i opened the driver the cmd/windows32/ opened and it was just black.
is this something i need to be worried about?

## Hardware/software information
Windows Version: 

Tablet Driver version:  v0.0.11

Tablet model: CTL-480

**Comment by hawku** [comment]
Need more info.

**Comment by Axellious** [comment]
windows 10:

when i opened the GUI the cmd opened and it was just blank with the caret just there.

**Comment by hawku** [comment]
Are you sure that you started the TabletDriverGUI.exe?
GUI is a Windows application, so it shouldn't open a command prompt window.

**Comment by Axellious** [comment]
is there any file in the folder that can make a blank cmd?

**Comment by hawku** [comment]
There should be any file that only shows a blank cmd.
