### ISSUE TITLE
Tablet as joystick, new meta mouse-controller alternative

### ISSUE THREAD

**Issue by AuracleTech** [hawku/TabletDriver#714]
I'd like to make a function to play on FPS games with the tablet, like the mouse option TD has, but if you come back towards the center, the cursor doesn't get dragged. Like a joystick. Kind of hard to explain, I never saw this anywhere.

I found out that playing with tablet on FPS games can give you super accuracy, but the fact that I have to leave the pen and go back to the center to reset position is very bad.

I'd need your discord and/or contact so I can work with you on this!
I can't label this as an enhancement more than an issue 😁

**Comment by AuracleTech** [comment]
![Skinn](https://user-images.githubusercontent.com/40531871/87233368-a8a23400-c394-11ea-9288-a11b2ffb0908.png)
Also I made myself a skin, didn't like the original

**Comment by Vlothx** [comment]
Welp, I can't understand how you want it to work. But uh... if I remember correctly there was a command in InfinityGhost's fork of TabletDriver so the cursor moves only when pressure is applied, might help with what you want to do?

**Comment by AuracleTech** [comment]
Not what I am trying to do :/
Hard to explain sadly... watch a video of someone gaming and imagine controlling using a tablet without leaving the tablet area or lifting the pen, this is what I am trying to do.

**Comment by AuracleTech** [comment]
I will close this issue as I don't know how to explain it further
