### ISSUE TITLE
Support for Huion H610 Pro V2

### ISSUE THREAD

**Issue by jstrw** [hawku/TabletDriver#722]
I recently got a Huion H610 Pro V2, and after installing the hawku tablet driver, it didn't recognize the tablet at all. I was wondering if support for the tablet will be implemented soon?

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: v0.2.3

Tablet model: Huion H610 Pro V2

**Comment by Vlothx** [comment]
No, since Hawku's stopped the development of this driver.

**Comment by jstrw** [comment]
Aw, I see. Thanks for the heads up c:
