### ISSUE TITLE
MTE-450 support please

### ISSUE THREAD

**Issue by ElderCub** [hawku/TabletDriver#73]
Would this be possible? I'm currently using very old bamboo drivers from 2014 because no newer drivers will support this tablet.

## Hardware/software information
Windows Version: Win10 x64

Tablet Driver version:  5.3.3-3

Tablet model: MTE-450

**Comment by hawku** [comment]
The driver should be able to detect the Wacom MTE-450.
Try the driver and tell me if it works.

**Comment by ElderCub** [comment]
It does work. Sorry, I should have checked before hand. You can add this to the list of supported models. Thank you.
