### ISSUE TITLE
[ERROR] Tablet not Found

### ISSUE THREAD

**Issue by Warwick4L** [hawku/TabletDriver#732]
It simply isn't detecting it. I don't have Wacom drivers either.

## Hardware/software information
Windows Version: Windows 10 1909 x64

Tablet Driver version: 0.2.3

Tablet model: 

XP-Pen G430S
--

**Comment by dimagtv** [comment]
I can help, open folder with driver and open the "config" and open "tablet.cfg" and add this code: https://pastebin.com/P2uUjQxx

**Comment by Warwick4L** [comment]
That worked, thank you so much!

**Comment by dimagtv** [comment]
> That worked, thank you so much!

Not problem!
