### ISSUE TITLE
tablet not found xp pen g640 

### ISSUE THREAD

**Issue by jahquintoo** [hawku/TabletDriver#736]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: xp pen star g640

**Comment by Vlothx** [comment]
You might have the new revision, [look at this please](https://www.reddit.com/r/osugame/comments/gwnrpv/important_xp_pen_released_a_new_g640/).

**Comment by jahquintoo** [comment]
yo thanks so much bro
