### ISSUE TITLE
Huion 608 support?

### ISSUE THREAD

**Issue by jxu** [hawku/TabletDriver#737]
I know it's an old tablet but it looks like it works, just that it detects as osu! tablet instead of the correct model and the area is confined to the very top left corner of the tablet.

## Hardware/software information
Windows Version:  8.1

Tablet Driver version: 0.2,3

Tablet model: Huion 608

**Comment by Vlothx** [comment]
I guess you could join the OpenTabletDriver discord and we could try making a config.
