### ISSUE TITLE
ctl471 180 rotation doesnt match the lefthand mode area position

### ISSUE THREAD

**Issue by BakaFlame** [hawku/TabletDriver#74]
180 rotation doesnt match the lefthand mode area position...
it has the wrong position, i was using **top right** tablet area in lefthand mode, same position in td but i have to move it to **bottom left** and do 180 rotation.
wacom driver cursor is lower than the td one, please fix this, it looks werid lol

and i thought the screen map section left & top offset can fix that problem, but it just changed my tablet position, i cant reach the edge of my screen...

## Hardware/software information
Windows Version: windows10 64bits

Tablet Driver version: 5.3-5-3

Tablet model: CTL471

**Comment by hawku** [comment]
Is that really that hard to understand?
180 degree rotation rotates the tablet area, not the tablet.
Tablet area arrow show the direction of the tablet area.

I will add "Left handed (Invert)" option in the next version.

**Comment by hawku** [comment]
@BakaFlame I've now added the left handed / tablet invert option to the latest version [v0.1.3.](http://hwk.fi/TabletDriver/TabletDriverV0.1.3.zip)
Is that easier to understand than the tablet area rotation option?

**Comment by shibou3** [comment]
@hawku Sorru for ask it in here but idk where else to ask, what is this "noise" filter?

**Comment by SuperTilted** [comment]
@shibou3 It's something to remedy [the shaky cursor that happens even when the pen is stationary](https://github.com/hawku/TabletDriver/wiki/FAQ#q-why-is-the-cursor-shaking).

**Comment by BakaFlame** [comment]
@hawku btw, it still doesnt match the original tablet area position! its still higher than the orignial cursor!
left handed works, but the position isnt right :((((

**Comment by hawku** [comment]
@BakaFlame Oh, sorry. Didn't notice that your tablet is Wacom CTL-471

The CTL-471 tablet size configuration is wrong.
I got the settings from the Wacom Linux driver and those are wrong in there too.

Edit the tablet.cfg and change the CTL-471 configuration to this:
```
#
# Wacom CTL-471
#
Tablet 0x056a 0x0300 0xFF0D 0x01
Name "Wacom CTL-471"
ReportLength 10
ButtonMask 0x40
MaxX 15200
MaxY 9500
MaxPressure 1023
Width 152.00
Height 95.00
InitFeature 0x02 0x02
```

Those settings will also be corrected in the next driver version, which will be out in few days time.

**Comment by hawku** [comment]
@BakaFlame The area size problem is fixed in the latest version.
