### ISSUE TITLE
TabletDriverGUI Dosen't open, No error code given.

### ISSUE THREAD

**Issue by JefBueno** [hawku/TabletDriver#742]
## Hardware/software information
Windows Version: Windows 7 64-bit RTM

Tablet Driver version: 0.2.3

Tablet model: Huion 420

I've installed the dependencies,drivers, and it dosen't want to open.
No, there is no previous huion driver installed.

**Comment by Vlothx** [comment]
Update your Windows version, stop using an insecure OS.

**Comment by JefBueno** [comment]
I'm on it, it just takes forever since my internet is slow, my pc broke down a few days ago and the only CD i had was the windows 7 one.

**Comment by JefBueno** [comment]
I fixed it by update to windows 10. Thank you Vlothx
