### ISSUE TITLE
Osu! window select area not showing

### ISSUE THREAD

**Issue by MeiFTW** [hawku/TabletDriver#748]
https://i.imgur.com/W14nOxZ.png

Osu! window showing like that. Anyone know why?

## Hardware/software information
Windows Version: Windows 10

Tablet Driver version:  0.2.3

Tablet model:  CTL-472

**Comment by Vlothx** [comment]
You aren't supposed to select your osu! window, you're supposed to select your entire monitor.

**Comment by MeiFTW** [comment]
I remember selecting Osu! window before and showing normally just like the entire screen. Is entire monitor the same as selecting Osu! window?
