### ISSUE TITLE
cursor moving like low fps

### ISSUE THREAD

**Issue by Garnet27** [hawku/TabletDriver#751]
my cursor shaking a lot and cutting off while moving, moving like low fps (I tried 125Hz / 1000Hz both but nothing changed) 

## Hardware/software information
Windows Version: 2004

Tablet Driver version: 0.2.3

Tablet model: CTL-480

**Comment by ssccoonniicc** [comment]
Windows 2004 broke smoothing, try https://www.github.com/pizzabelly/TabletDriver or https://www.github.com/AbdShullah/TabletDriver

**Comment by Garnet27** [comment]
> Windows 2004 broke smoothing, try https://www.github.com/pizzabelly/TabletDriver or https://www.github.com/AbdShullah/TabletDriver

Thx a lot!
