### ISSUE TITLE
Support for CTL-6100 (basically CTL4100 but bigger)

### ISSUE THREAD

**Issue by Cailus** [hawku/TabletDriver#753]
## Hardware/software information
Windows Version:  win10

Tablet Driver version: latest

Tablet model: wacom CTL6100.
It doesn't work with a CTL6100. Would you please add support to CTL6100? It's just like the CTL4100 but with a bigger size. Thanks.

**Comment by Ahin0223** [comment]
but TabletDriverGUI not updated now?
