### ISSUE TITLE
Tablet Driver is not working for Star g430S

### ISSUE THREAD

**Issue by Veloctyy** [hawku/TabletDriver#755]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 0.2.3

Tablet model: Star G430S

When i try to use the tablet drivers its says its not connected like everyone else's problem. Also when i exit out of the driver it says "Some files from TabletDriverV0.2.3.zip were modified or new files were created. Do you wish to put them in archive?"
and i  downloaded vmulti and installed all Pentablet drivers and folders
![Annotation 2020-08-06 103729](https://user-images.githubusercontent.com/69313125/89545054-dc744c00-d7d0-11ea-9924-bf17384bda8a.png)

Please help

**Comment by ssccoonniicc** [comment]
Extract TabletDriver, don't use it from inside the zip file and add the g430s_B config if needed: https://www.reddit.com/r/osugame/comments/dnwtdk/potential_fix_for_xppen_g430s_and_community/. Also make sure you dont have any xp-pen drivers installed.

**Comment by Veloctyy** [comment]
@ssccoonniicc when i open the drivers (and its not zip) its says the vmulti drivers wont open 
![Capture](https://user-images.githubusercontent.com/69313125/89600202-77037800-d82f-11ea-8d51-5da99fbbacb1.PNG)

**Comment by ssccoonniicc** [comment]
install vmulti and try to run TabletDriver as administrator

**Comment by Veloctyy** [comment]
i did multiple times i even installed 64 and 32 bit and the regular vmulti

**Comment by Veloctyy** [comment]
Ok so, xp pen made it so you can only use their drivers. So if you use an xp pen you should use this for the driver 
![Screenshot_21](https://user-images.githubusercontent.com/69313125/96208347-4892cf00-0f3b-11eb-9461-cab7ea6c5728.png)
I hope this helped anyone who needed it. :)
