### ISSUE TITLE
Do not know how to remove gliding when dragging

### ISSUE THREAD

**Issue by AvevoN** [hawku/TabletDriver#779]
I want to start dragging when I play osu! but there is this thing where the cursor glides to its position. I find this very annoying and want to disable it, however I don't know how. This does not happen on the Xp-Pen drivers. Can anyone help?

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: Xp-Pen G640

**Comment by Hyenook** [comment]
Check if you have any filter enabled, i.e Smoothing or Noise reduction filter

**Comment by AvevoN** [comment]
I have set all of the values to 0 or the lowest they can go. I even set the mouse scroll values to 0 as well. The cursor still glides. Or do I need the filters enabled?

**Comment by Hyenook** [comment]
Just make sure that all the filters are disabled. Also, are you completely sure that TabletDriver is properly accesing your tablet? What I mean is that XP-Pen released another revision of the G640 and fucked up some stuff, making it incompatible with TabletDriver (unless you put the proper config)

**Comment by AvevoN** [comment]
I am using the config that I found from a reply to an issue regarding the Star G640 not connecting (LINK: https://github.com/hawku/TabletDriver/issues/602).
1: Is this the _proper config_ that you said?
2: Do you think this config is the cause of the cursor gliding even with the filters disabled?

**Comment by Hyenook** [comment]
Well, as you might know, XP-Pen released a new revision (the one you're using right now) where they fucked up the hardware smoothing, that might be the reason of the _cursor glide_. But I'm not sure, would recommend testing on another computer.

**Comment by AvevoN** [comment]
Oh, okay. Thanks for the help!
