### ISSUE TITLE
Tablet not found xp pen g430s

### ISSUE THREAD

**Issue by Aena1** [hawku/TabletDriver#794]
## Hardware/software information
Windows Version: 

Tablet Driver version: v0.1.5.5 Devocub Edition with Antichatter

Tablet model:Xp pen g430s 
![image](https://user-images.githubusercontent.com/70045669/92012853-ff841400-ed1a-11ea-8986-cc9838da7f29.png)

**Comment by Aena1** [comment]
tried changing the config and got rid of all XP pen drivers still wont fix

**Comment by Hyenook** [comment]
You probably have the B revision of the G430S, try with InfinityGhost's fork of TabletDriver
