### ISSUE TITLE
Tablet not found! Driver stopped. Restarting! (XP pen Star G640)

### ISSUE THREAD

**Issue by Weebzard** [hawku/TabletDriver#795]
This is what happens after I launch the TabletDriver GUI, I made sure to install everything and to restart my computer but it's still the same thing. I restarted a lot of times and even uninstalled then reinstalled the driver, still the same. Can someone help me please, I don't have a lot of knowledge in programmation in general so I'm struggling a lot.

![Capture d’écran (124)](https://user-images.githubusercontent.com/70770528/92266991-74ed1180-eee0-11ea-81db-98e7e2968280.png)

## Hardware/software information
Windows Version: Microsoft Windows NT 6.2.9200.0

Tablet Driver version: 0.1.5.5

Tablet model: XP pen Star G640

**Comment by Hyenook** [comment]
Look at this video: https://www.youtube.com/watch?v=m2aJDX5730I
