### ISSUE TITLE
Different looks of the driver

### ISSUE THREAD

**Issue by inyafaze** [hawku/TabletDriver#799]
Hey hawku, something has been bothering me for a long time now.

My driver looks like this: https://gyazo.com/acc1b942ae2fe4a56e5c45a6e0143f81 (CTL-470)
I have every function i want to have and I'm totally satisfied with this program.

Now my friend's driver looks like this: https://gyazo.com/6b71d122832c3b6a993168ad3e1353fd (CTL4100)
with buttons, misc etc. on top 

Also i have a "apply" and a "save" button, whereas my friend only has "save settings"

Why is it like that? My friend has no antichatter or prediction for example, is it because of his tablet being different?

My other friend also owns a CTL-470 like me and he doesn't have any settings except Area at all.
No smoothing, anti-chatter and no prediction.
He plays on a cheap setup and i wanted him to atleast have a smooth cursor but it's not working.

Can you help me with this issue? 

Greetings, inya

## Hardware/software information
Windows Version: windows 10 

Tablet Driver version: v0.2.3

Tablet model: CTL-470 ; CTL4100

**Comment by RikkaWls** [comment]
It looks like you have the devo cub driver installed not hawku or maybe an older version
