### ISSUE TITLE
hover smoothing on ctl-490

### ISSUE THREAD

**Issue by Peachy-Cai** [hawku/TabletDriver#8]
These drivers are a godsend its amazing, when i use my pen with a taped nib it's way smoother and clearer than it ever was,,

but when its not taped theres still input lag (a lot less tho) when hovering, do you think its possible to remove it entirely?  Thanks so much for doing this holy shit you're a legend

**Comment by CSharpProgramming** [comment]
Nope the smoothing on the ctl-490 is entirely hardware based :/

**Comment by Peachy-Cai** [comment]
how do we know this o:
