### ISSUE TITLE
Area not changing

### ISSUE THREAD

**Issue by hiImkira** [hawku/TabletDriver#81]
For some reason when I try to change my area and stuff, I click save and apply and it still stays at full area but on the program it shows https://gyazo.com/18e83cc998460f8f83367c5612e3950f

## Hardware/software information
Windows Version:  Windows 10 Pro 64-bit

Tablet Driver version: v0.1.3

Tablet model: Wacom CTH-480

**Comment by hawku** [comment]
You have the Wacom drivers still installed on your system.
TabletDriverGUI window title says "(Wacom drivers installed)".

If you have problems uninstalling the Wacom drivers, check the issue #1
