### ISSUE TITLE
Mouse1 button not working anymore

### ISSUE THREAD

**Issue by Nizis** [hawku/TabletDriver#819]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: CTL-480

**Comment by Nizis** [comment]
After installing the drivers, my mouse and tablet mouse1's don't work. Mouse2 and scrolling still work

**Comment by ykhurshid** [comment]
Did you manage to solve your problem? Why is the issue closed? I'm stuck with the exact same problem.
