### ISSUE TITLE
Screen map is not correct

### ISSUE THREAD

**Issue by Master433** [hawku/TabletDriver#82]
As the title says, the screen mapping isn't correct. I have set the Driver to map the whole screen but my tablet only affects the lower right portion of the screen. Not only that but I set my tablet area setting to aspect ratio but it still uses the full area.

Here's a pic of the driver settings:
![xppen](https://user-images.githubusercontent.com/37858532/38009454-0574af92-3287-11e8-8db1-db7a1a67166e.png)

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.3

Tablet model: XP-Pen G430S

**Comment by Chrysphylax** [comment]
Did you click restart driver? You need to do that for any changes to occur

**Comment by hawku** [comment]
XP-Pen G430S is not support by this driver. Currently there isn't a way to detect if the tablet is G430, G430S or G540. I will try to make a detection for the G540 when I get one in my hands.

XP-Pen is using the same USB product id for different products. That causes problems with this driver and with the XP-Pen's own drivers.
