### ISSUE TITLE
Pen pressure does not work in photoshop

### ISSUE THREAD

**Issue by BYSTACK** [hawku/TabletDriver#84]
It doesn't seem to work anywhere except windows ink

## Hardware/software information
Windows Version: Windows 10 x64
Tablet Driver version: 0.1.3
Tablet model: XP Pen G640

**Comment by hawku** [comment]
The driver is made to be used with osu!, so the pen pressure support is not the priority.
Only the Windows Ink mode supports the pen pressure.

The WinTab interface is not supported by this driver.
I think that adding the WinTab support would need more code, testing and troubleshooting than the rest of the driver.

If someone wants to add the WinTab support to this driver, then this might be a good starting point:
https://github.com/perlfu/WintabEmulator
