### ISSUE TITLE
Can't change tablet area

### ISSUE THREAD

**Issue by xsuos** [hawku/TabletDriver#851]
I change my tablet area, press save settings, and nothing happens. 

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.2.3

Tablet model: XP-Pen Deco 01 V2

**Comment by Zinquay** [comment]
yo bro have you fixed this issue yet? I'm getting it too, I put my area to 45, disable full area, and save settings, and it even shows a smaller area, but its stuck on full area and idk what to do.. have you found a fix yet?

**Comment by xsuos** [comment]
No I just went back to xp pen drivers
