### ISSUE TITLE
Liftoff distance

### ISSUE THREAD

**Issue by Victrixen** [hawku/TabletDriver#86]
## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.1.3

Tablet model: CTL 490

The liftoff distance seems to be tiny, when im making jumps in osu the cursor teleports sometimes when the pen is 1/3 of an inch from the tablet.

**Comment by Victrixen** [comment]
Just did a better measurement and it's less than 1 cm liftoff distance :(

**Comment by Kurumya** [comment]
Try to add like 10ms Smoothing filter latency with 500Hz.

**Comment by hawku** [comment]
@Victrixen Did you measure that with the official Wacom drivers?
Taping the pen tip might lower the maximum hover height.
