### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by Noaturr** [hawku/TabletDriver#88]
I had my system reinstalled, installed every vcredist i could find, but first i was getting an "missing vcruntime140.dll" and "missing msvcp140.dll" while trying to run drivers, so i downloaded and installed them manually, then reinstalled vmultidriver, now im getting just "application did not start correctly (0xc000007b). Press OK to end application"

## Hardware/software information
Windows Version:  10pro

Tablet Driver version: latest

Tablet model: Wacom one

**Comment by Dico200** [comment]
please specify the exact model of your wacom tablet.

**Comment by Noaturr** [comment]
@Dico200 I guess its CTL-471

**Comment by hawku** [comment]
@Noaturr 
https://github.com/hawku/TabletDriver#installation

**Comment by Noaturr** [comment]
@hawku i did it, tho it didn`t help me at all
But, like a minute ago i installed wacom drivers, then i uninstalled them, and now it works
still, thanks for the help!
