### ISSUE TITLE
Please Help !Unsupported tablet -- Wacom pth-460 

### ISSUE THREAD

**Issue by whotf1** [hawku/TabletDriver#885]
## Hardware/software information
Windows Version:  Windows 10, 64b

Tablet Driver version:  V0.2.3

Tablet model: Wacom pth-460

**Comment by whotf1** [comment]
This is really annoying and help would be greatly appreciated, this tablet is well-deserving of being able to play osu well, unfortunately, without the driver, it's difficult for the tablet to keep up, small latency problems and such, I'm confident this driver will make it perform flawlessly!

**Comment by MiloCohenElyanow** [comment]
drff
