### ISSUE TITLE
Pen Pressure no longer works on Huion H420

### ISSUE THREAD

**Issue by VideoGameBoi** [hawku/TabletDriver#888]
Trying to use pen pressure on my drawing tablet (for use on art programs) no longer works.

## Hardware/software information
Windows Version: Windows 7

Tablet Driver version: 0.2.3

Tablet model: Huion H420

**Comment by Greenpitbulll** [comment]
Check which mode you are currently using. If you are using the Absolute (osu!) mode, then pen pressure will not be taken into account. If you want to enable pen pressure, change the mode to Windows Ink (Draw).

**Comment by VideoGameBoi** [comment]
thank you
