### ISSUE TITLE
Hope for Gaomon 1060PRO

### ISSUE THREAD

**Issue by mashirozx** [hawku/TabletDriver#90]
## Hardware/software information
Windows Version: Microsoft Windows NT 6.2.9200.0

Tablet Driver version: 0.1.4

Tablet model: Gaomon 1060PRO

**Comment by riley-badour** [comment]
I can help you get your tablet supported i just need you to get need some information about your tablet

**Comment by MyAngelXiaoYing** [comment]
> I can help you get your tablet supported i just need you to get need some information about your tablet

i can give you 1060Pro Driver and Manual about device or more i have one but i don't know how to see it.
this driver is fxxk because have two ver,one for 8192 sense and other one is nothing,i will upload two of driver.
link:https://drive.google.com/open?id=1MU-e1uv5BW0fEUkqmL48iGzdD4Up4Qu-

**Comment by MyAngelXiaoYing** [comment]
> I need the startlogup.txt file. When you run the hawku tablet drivers

sure
https://drive.google.com/open?id=1LnXa4wfsqiagbDIN0G4iLyoHnmd6Qq-y

**Comment by riley-badour** [comment]
Did you install the vmuti drivers also can you do the HIDlist command in the drivers and give me a copy of the output.

**Comment by MyAngelXiaoYing** [comment]
> Did you install the vmuti drivers also can you do the HIDlist command in the drivers and give me a copy of the output.

wtf i install vmuti and
[2019-01-18 11:40:48.477] >> Start
[2019-01-18 11:40:48.481] TabletDriver started!
[2019-01-18 11:40:48.481] [STATUS] TABLET Unknown Huion Tablet! Check startuplog.txt!
[2019-01-18 11:40:48.481] [STATUS] USB {62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}
[2019-01-18 11:40:48.481] [STATUS] WIDTH 100.00000
[2019-01-18 11:40:48.481] [STATUS] HEIGHT 100.00000
[2019-01-18 11:40:48.481] [STATUS] MAX_X 10000
[2019-01-18 11:40:48.481] [STATUS] MAX_Y 10000
[2019-01-18 11:40:48.481] [STATUS] MAX_PRESSURE 2047
[2019-01-18 11:40:48.481] [STATUS] AUX_BUTTONS 0
[2019-01-18 11:40:48.481] >> Log Off
https://drive.google.com/open?id=18DnK3lS9-itsPQ7SGQ_UV9phiqI-Q8A0
can't move btw

**Comment by MyAngelXiaoYing** [comment]
> Did you install the vmuti drivers also can you do the HIDlist command in the drivers and give me a copy of the output.

can move but just up left little area

**Comment by riley-badour** [comment]
lets just say your tablet and my tablet are the same thing 1060 plus 8192
#
# Huion/Gaomon 1060PRO
#
USBTablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}"
CheckString 6 "1060PRO"
Name "Huion/Gaomon 1060PRO"
ReportId 0x08
ReportLength 8
DetectMask 0x80
IgnoreMask 0x60
MaxX 50800
MaxY 31750
MaxPressure 2047
Width 254
Height 158.75
InitStrings 100 200
AuxReportId 0x08
AuxReportLength 8
AuxDetectMask 0xE0
AuxgnoreMask 0x80
AuxCustomData ReportId Source=0
AuxCustomData ButtonsLow Source=4
AuxCustomData ButtonsHigh Source=5
AuxCustomData Detect Source=1
AuxButtonCount 12

**Comment by MyAngelXiaoYing** [comment]
> lets just say your tablet and my tablet are the same thing 1060 plus 8192
> 
> # Huion/Gaomon 1060PRO
> USBTablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}"
> CheckString 6 "1060PRO"
> Name "Huion/Gaomon 1060PRO"
> ReportId 0x08
> ReportLength 8
> DetectMask 0x80
> IgnoreMask 0x60
> MaxX 50800
> MaxY 31750
> MaxPressure 2047
> Width 254
> Height 158.75
> InitStrings 100 200
> AuxReportId 0x08
> AuxReportLength 8
> AuxDetectMask 0xE0
> AuxgnoreMask 0x80
> AuxCustomData ReportId Source=0
> AuxCustomData ButtonsLow Source=4
> AuxCustomData ButtonsHigh Source=5
> AuxCustomData Detect Source=1
> AuxButtonCount 12

Huion and Gaomon all just rebrand,Huion for US,Gaomon for China.
any way thank <3

**Comment by riley-badour** [comment]
so wait it works how about the buttons  also does you tablet have full area 
![image](https://user-images.githubusercontent.com/38139326/51365296-91d79580-1aad-11e9-890e-6c2f1e0efe12.png)
for me my 1060 cuts out around the half was through  soft button 16
and tiny bit on the bottom is that the same for you

**Comment by MyAngelXiaoYing** [comment]
> here try this one
> 
> #Huion/Gaomon 1060PRO
> 
> USBTablet "{62F12D4C-3431-4EFD-8DD7-8E9AAB18D30C}"
> CheckString 6 "1060PRO"
> Name "Huion/Gaomon 1060PRO"
> ReportId 0x07
> ReportLength 8
> DetectMask 0x80
> IgnoreMask 0x60
> MaxX 50800
> MaxY 31750
> MaxPressure 2047
> Width 254
> Height 158.75

ok this work,now i just troubled with area,gaomon driver area to wacom area.

**Comment by riley-badour** [comment]
> 
> 
> so wait it works how about the buttons also does you tablet have full area
> ![image](https://user-images.githubusercontent.com/38139326/51365296-91d79580-1aad-11e9-890e-6c2f1e0efe12.png)
> for me my 1060 cuts out around the half was through soft button 16
> and tiny bit on the bottom is that the same for you the blue outline

this again ^^^ also could you hit all 12 buttons with debug on without your pen  near the tablet to so i can get that working

**Comment by MyAngelXiaoYing** [comment]
> > so wait it works how about the buttons also does you tablet have full area
> > ![image](https://user-images.githubusercontent.com/38139326/51365296-91d79580-1aad-11e9-890e-6c2f1e0efe12.png)
> > for me my 1060 cuts out around the half was through soft button 16
> > and tiny bit on the bottom is that the same for you the blue outline
> 
> EDIT: wow so the 1060 pro is only a 8 button that's nice
> ![](https://camo.githubusercontent.com/69bd7233aa2623714dada6dbba69cdba1c17c3c1/68747470733a2f2f696d616765732d6e612e73736c2d696d616765732d616d617a6f6e2e636f6d2f696d616765732f492f363164506b4642777a424c2e5f534c313230305f2e6a7067)
> 
> this again ^^^ also could you hit all 8 buttons with debug on without your pen near the tablet to so i can get that working but thanks so far with your data

a little problem,Gaomon 1060pro have two ver,8192 2048,my friend is 8192 ver,so....
https://drive.google.com/open?id=11ZnjRvz24mNsNnXs7Tyfgs6kyd0T98_A
his log

**Comment by riley-badour** [comment]
@hawku this other person 1060 tablet is mine but its OEM02_T174 instead of Huion_174 i am thinkng they are the same tablet just with a oem identifier. Dont know if you should need another config or a check tablet string with a or Command

**Comment by redolence** [comment]
Hello, by any chance you can make OEM02_T174_181125 supported ?

**Comment by Stealthstarcat** [comment]
Hi,
I have a 1060 Plus. I have the button options available per using the above added aux code. I've assigned keys to them, but they don't work. What should I do different?
