### ISSUE TITLE
Feature Require: Auto update

### ISSUE THREAD

**Issue by Mother-Ship** [hawku/TabletDriver#91]
Thanks ._.

**Comment by skipfie** [comment]
+1 for this

**Comment by Kurumya** [comment]
Driver full optimisation and more model support before useless autoupdate setting, hawku may have better to do ._.

**Comment by hawku** [comment]
I will not add auto update until the driver is stable enough.
There is a high possibility that the new version of the driver might break something, so it wouldn't be very smart to automatically update the latest version to 15000 users.

Currently the latest updates mostly just fixes problems that prevents people using the driver, so 99 percent of the users wont even need the latest version.
