### ISSUE TITLE
Problem with left-handed mode, wacom ctl-471

### ISSUE THREAD

**Issue by badoq** [hawku/TabletDriver#93]
Hey! I have annoying problem with left-handed mode. I can't use tablet on left-handed mode, even when I set 180 deg. I tried everything, any helpful advices for me please?

## Hardware/software information
Windows Version: Windows 10 NT

Tablet Driver version: 0.1.4V

Tablet model: Wacom ctl-471

**Comment by hawku** [comment]
You didn't tell what is the problem?
You enabled the left handed mode and set rotation 0 and that doesn't work???

**Comment by badoq** [comment]
yes

**Comment by hawku** [comment]
Please, tell what is the problem.

**Comment by badoq** [comment]
Tablet doesn't react for left-handed mode, for 180 deg too, it's still being right-handed.

**Comment by hawku** [comment]
Did you save or apply the settings?

**Comment by badoq** [comment]
Of course.

**Comment by hawku** [comment]
Attach the startuplog.txt from the driver's folder to a GitHub comment

**Comment by badoq** [comment]
![image](https://user-images.githubusercontent.com/38009712/38201975-726b65c0-369a-11e8-901c-4a5e9734eb44.png)

I have something like that, but i have not any wacom driver.

**Comment by badoq** [comment]
[startuplog.txt](https://github.com/hawku/TabletDriver/files/1868441/startuplog.txt)

**Comment by hawku** [comment]
You have some Wacom drivers installed.
Windows might have automatically installed the Wacom drivers.
Check the issue #1

**Comment by badoq** [comment]
Thanks, it works now.
