### ISSUE TITLE
[VMULTI] [XP-Pen Star G640S] Tablet Init failed, Devcon.exe failed.

### ISSUE THREAD

**Issue by SpicyDice** [hawku/TabletDriver#940]
I saw a couple of issues like this, devcon.exe and tablet init failed, just caring to bring this up once again and hopefully this really gets resolved.

## Hardware/software information
Windows Version: Windows 10 20H2 64-Bit

Tablet Driver version: 0.2.3

Tablet model: XP-Pen Star G640S

## Devcon.exe failed.

If I try to execute **install_vmulti_driver.bat** without running as admin, the bat does not request for admin permissions as it supposed to give me a prompt and instead gave me this:
```
  Are you sure you want to install vmulti driver?

Press enter to install...
C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM  --> Check for permissions

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>"C:\WINDOWS\system32\cacls.exe" "C:\WINDOWS\system32\config\system"   1>nul 2>&1

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM --> If error flag set, we do not have admin.

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if '0' NEQ '0' (
echo Requesting administrative privileges...
 goto UACPrompt
)  else (goto gotAdmin  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if exist "C:\Users\C\AppData\Local\Temp\getadmin.vbs" (del "C:\Users\CAppData\Local\Temp\getadmin.vbs"  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>pushd "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>CD /D "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>devcon.exe /r install vmulti.inf pentablet\hid
devcon.exe failed.
Press enter...
```
Expected out come: Give out a UAC prompt to give admin permission.
What happened: It executed devcon.exe straight ahead without admin permissions, therefore it failed.

## Running install_vmulti_driver.bat as administrator
-- > When I run the bat **install_vmulti_driver.bat** as administrator, the bat just *immediately disappears* without any prompt after pressing **enter**.

However, going into the **driver_vmulti** folder where the 64 bit driver is located of course, executing the bat **install_vmulti_64.bat** without any admin permissions, it does not request or asks for admin permissions and instead gave me an outcome of **devcon.exe failed** similar above.
```
C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM  --> Check for permissions

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>"C:\WINDOWS\system32\cacls.exe" "C:\WINDOWS\system32\config\system"   1>nul 2>&1

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM --> If error flag set, we do not have admin.

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if '0' NEQ '0' (
echo Requesting administrative privileges...
 goto UACPrompt
)  else (goto gotAdmin  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if exist "C:\Users\C\AppData\Local\Temp\getadmin.vbs" (del "C:\Users\CAppData\Local\Temp\getadmin.vbs"  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>pushd "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>CD /D "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>devcon.exe /r install vmulti.inf pentablet\hid
devcon.exe failed.
Press enter...
```

## How I resolved Devcon.exe failed

**But** if I run **install_vmulti_64.bat** from the driver_multi folder as administrator, the driver installs as expected.

```
C:\WINDOWS\system32>REM  --> Check for permissions

C:\WINDOWS\system32>"C:\WINDOWS\system32\cacls.exe" "C:\WINDOWS\system32\config\system"   1>nul 2>&1

C:\WINDOWS\system32>REM --> If error flag set, we do not have admin.

C:\WINDOWS\system32>if '0' NEQ '0' (
echo Requesting administrative privileges...
 goto UACPrompt
)  else (goto gotAdmin  )

C:\WINDOWS\system32>if exist "C:\Users\C\AppData\Local\Temp\getadmin.vbs" (del "C:\Users\C\AppData\Local\Temp\getadmin.vbs"  )

C:\WINDOWS\system32>pushd "C:\WINDOWS\system32"

C:\WINDOWS\system32>CD /D "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>devcon.exe /r install vmulti.inf pentablet\hid
Device node created. Install is complete when drivers are installed...
Updating drivers for pentablet\hid from C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\vmulti.inf.
Drivers installed successfully.
Press enter...
```
## Summing it up
To sum it up, upon pressing enter after executing **install_vmulti_driver.bat** it executes **install_vmulti_64.bat** right, but as it reaches **install_vmulti_64.bat**, it didn't give UAC prompt for admin permissions, if I run **install_vmulti_driver.bat** as administrator it disappears without any prompt, however if I just go to the folder **driver_vmulti** manually and run **install_vmulti_64.bat** as administrator directly, it gets the job done and installs the drivers.

*The 32 bit versions of both .bat install and remove driver files work seemlessly and they give me a prompt for admin permissions, but they obviously wont going to technically work because I'm in a 64 bit OS*

## remove_vmulti_driver.bat
Again, upon pressing enter, the .bat then directs it to remove_vmulti_64.bat but does not ask for admin permissions so it gave an "access denied"
**But** running it as administrator, the bat just disappears immediately, the same way like installing the driver.

## Execution of remove_vmulti_64.bat in the driver_vmulti folder without admin permissions
The **remove_vmulti_64.bat**, gave an "access denied" when just running it without admin permissions, it ignored the lines of code in the .bat file to ask for admin permissions for some reason the same way as installing the driver
```
C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM  --> Check for permissions

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>"C:\WINDOWS\system32\cacls.exe" "C:\WINDOWS\system32\config\system"   1>nul 2>&1

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>REM --> If error flag set, we do not have admin.

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if '0' NEQ '0' (
echo Requesting administrative privileges...
 goto UACPrompt
)  else (goto gotAdmin  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>if exist "C:\Users\C\AppData\Local\Temp\getadmin.vbs" (del "C:\Users\C\AppData\Local\Temp\getadmin.vbs"  )

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>pushd "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>CD /D "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>DIFxCmd.exe /u vmulti.inf
DIFxAPI Sampe Program
INFO: Option "/u"
INFO: Input file "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\vmulti.inf"
INFO: Flags 0x0 (0)

TEST: uninstalling driver package.
LOG Event: 1, ENTER:  DriverPackageUninstallW
LOG Event: 3, Access denied! Administrator account required.
LOG Event: 1, RETURN: DriverPackageUninstallW  (0x5)
ERROR: failed with error code 0x5

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>devcon.exe remove pentablet\hid
ROOT\HIDCLASS\0000                                          : Remove failed
No devices were removed.
Press enter...
```
## My solution to remove the vmutli driver successfully
It gets the job done If I manually run **remove_vmulti_64.bat** from driver_vmulti as administrator, similar to the way I installed the driver.
```
C:\WINDOWS\system32>REM  --> Check for permissions

C:\WINDOWS\system32>"C:\WINDOWS\system32\cacls.exe" "C:\WINDOWS\system32\config\system"   1>nul 2>&1

C:\WINDOWS\system32>REM --> If error flag set, we do not have admin.

C:\WINDOWS\system32>if '0' NEQ '0' (
echo Requesting administrative privileges...
 goto UACPrompt
)  else (goto gotAdmin  )

C:\WINDOWS\system32>if exist "C:\Users\C\AppData\Local\Temp\getadmin.vbs" (del "C:\Users\C\AppData\Local\Temp\getadmin.vbs"  )

C:\WINDOWS\system32>pushd "C:\WINDOWS\system32"

C:\WINDOWS\system32>CD /D "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\"

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>DIFxCmd.exe /u vmulti.inf
DIFxAPI Sampe Program
INFO: Option "/u"
INFO: Input file "C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\vmulti.inf"
INFO: Flags 0x0 (0)

TEST: uninstalling driver package.
LOG Event: 1, ENTER:  DriverPackageUninstallW
LOG Event: 1, Uninstalling driver package C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\vmulti.inf...
LOG Event: 1, Successfully uninstalled 'C:\WINDOWS\INF\oem3.inf'.
LOG Event: 0, Device with device instance ID 'ROOT\HIDCLASS\0000' reinstalled.
LOG Event: 1, Successfully uninstalled 1 devices for C:\WINDOWS\System32\DriverStore\FileRepository\vmulti.inf_amd64_e6ed10438a09edd9\vmulti.inf.
LOG Event: 1, Successfully deleted properties for driver store entry 'C:\WINDOWS\System32\DriverStore\FileRepository\vmulti.inf_amd64_e6ed10438a09edd9\vmulti.inf'.
LOG Event: 0, Uninstall completed.
LOG Event: 1, RETURN: DriverPackageUninstallW  (0x0)
SUCCESS: uninstalled driver package C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti\vmulti.inf.

C:\Users\C\Desktop\TabletDriverV0.2.3\driver_vmulti>devcon.exe remove pentablet\hid
ROOT\HIDCLASS\0000                                          : Removed
1 device(s) were removed.
Press enter...
```

## Code in the .bat file that is supposed to request admin permissions
Most likely, these lines of code in the install_vmulti.bat is completely ignored upon execution for some reason, therefore Devcon.exe and the removal bat files for drivers can't do their job properly because it did not receive admin permissions, it did not give out UAC prompt.
```
:: BatchGotAdmin  
:-------------------------------------  
REM  --> Check for permissions  
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"  
  
REM --> If error flag set, we do not have admin.  
if '%errorlevel%' NEQ '0' (  
    echo Requesting administrative privileges...  
    goto UACPrompt  
) else ( goto gotAdmin )  
  
:UACPrompt  
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"  
    echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"  
  
    "%temp%\getadmin.vbs"  
    exit /B  
  
:gotAdmin  
    if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
```

I am bringing this issue with much info as a I can, maybe there are some users out there with different tablets getting this same issue. and hopefully this info is useful enough to get a possible solution in the future.

## Tablet init failed - My last unresolved issue

Upon *successful installation of the vmultidriver (64 bit)* I get this error upon connecting the tablet and then clicking restart driver TabletDriverGUI, **application was executed with admin permissions**, I don't understand, since star g640s is listed as one of the supported tablets in the readme.md.
Pentablet drivers, the official ones from XP-Pen were uninstalled cleanly and correctly before I installed the vmultidriver from TabletDriverV0.2.3

```
[2020-12-28 14:18:43.961] 
[2020-12-28 14:18:43.961]   Driver version: 0.2.3
[2020-12-28 14:18:43.961]   Windows version: Microsoft Windows NT 6.2.9200.0
[2020-12-28 14:18:43.961]   Windows product: Windows 10 Enterprise
[2020-12-28 14:18:43.961]   Windows release: 2009
[2020-12-28 14:18:43.961] 
[2020-12-28 14:18:43.961] >> CheckTablet
[2020-12-28 14:18:43.961] >> DesktopSize 1024 768
[2020-12-28 14:18:43.962] Desktop size = (1024.00 px x 768.00 px)
[2020-12-28 14:18:43.962] >> ScreenArea 1024 768 0 0
[2020-12-28 14:18:43.962] Screen area = (w=1024.00, h=768.00, x=0.00, y=0.00)
[2020-12-28 14:18:43.962] >> TabletArea 66.67 50 40 25
[2020-12-28 14:18:43.962] Tablet area: (66.67 mm x 50.00 mm X+40.00 mm Y+25.00 mm)
[2020-12-28 14:18:43.962] >> Rotate 0
[2020-12-28 14:18:43.962] Rotation matrix = [1.000000,-0.000000,0.000000,1.000000]
[2020-12-28 14:18:43.962] >> OutputMode Absolute
[2020-12-28 14:18:43.962] Output Mode = Absolute
[2020-12-28 14:18:43.962] >> ClearButtonMap
[2020-12-28 14:18:43.962] Pen button map cleared!
[2020-12-28 14:18:43.962] >> ButtonMap 1 "MOUSE1"
[2020-12-28 14:18:43.962] Pen button 1 mapped to 'MOUSE1'
[2020-12-28 14:18:43.962] >> ButtonMap 2 "MOUSE2"
[2020-12-28 14:18:43.962] Pen button 2 mapped to 'MOUSE2'
[2020-12-28 14:18:43.962] >> ButtonMap 3 "MOUSE3"
[2020-12-28 14:18:43.962] Pen button 3 mapped to 'MOUSE3'
[2020-12-28 14:18:43.962] >> ClearAuxButtonMap
[2020-12-28 14:18:43.962] Aux button map cleared!
[2020-12-28 14:18:43.962] >> PressureSensitivity 0
[2020-12-28 14:18:43.962] Tablet pressure sensitivity = 0.00000
[2020-12-28 14:18:43.962] >> PressureDeadzone 0
[2020-12-28 14:18:43.963] Tablet pressure deadzone = 0.00
[2020-12-28 14:18:43.963] >> ScrollSensitivity 0.5
[2020-12-28 14:18:43.963] Tablet scroll sensitivity = 0.50 scrolls per millimeter
[2020-12-28 14:18:43.963] >> ScrollAcceleration 1
[2020-12-28 14:18:43.963] Tablet scroll acceleration = 1.00
[2020-12-28 14:18:43.963] >> ScrollStopCursor false
[2020-12-28 14:18:43.963] Tablet scroll stop cursor = false
[2020-12-28 14:18:43.963] >> FilterTimerInterval 10
[2020-12-28 14:18:43.963] Filter Timer Interval = 10 (100.00 Hz)
[2020-12-28 14:18:43.963] >> Smoothing 0
[2020-12-28 14:18:43.963] Smoothing = off
[2020-12-28 14:18:43.963] >> Noise 0
[2020-12-28 14:18:43.963] Noise Reduction = off
[2020-12-28 14:18:43.963] >> AntiSmoothing 0
[2020-12-28 14:18:43.963] Anti-smoothing = off
[2020-12-28 14:18:43.963] >> Debug true
[2020-12-28 14:18:43.963] Debug logging = True
[2020-12-28 14:18:43.963] >> Info
[2020-12-28 14:18:43.964] 
[2020-12-28 14:18:43.964] VMulti: XP-Pen
[2020-12-28 14:18:43.964] 
[2020-12-28 14:18:43.964] Tablet: XP-Pen G640s
[2020-12-28 14:18:43.964]   Width = 160.00 mm
[2020-12-28 14:18:43.964]   Height = 100.00 mm
[2020-12-28 14:18:43.964]   Max X = 32000
[2020-12-28 14:18:43.964]   Max Y = 20000
[2020-12-28 14:18:43.964]   Max Pressure = 8191
[2020-12-28 14:18:43.964]   Click Pressure = 0
[2020-12-28 14:18:43.964]   Keep Tip Down = 0 reports
[2020-12-28 14:18:43.964]   Report Id = 0x02
[2020-12-28 14:18:43.964]   Report Length = 10 bytes
[2020-12-28 14:18:43.970]   Detect Mask = 0x80
[2020-12-28 14:18:43.970]   Ignore Mask = 0x00
[2020-12-28 14:18:43.970]   Pen button map = 'MOUSE1' 'MOUSE2' 'MOUSE3' 
[2020-12-28 14:18:43.970]   Aux button count = 0
[2020-12-28 14:18:43.970]   Init report: { 0x02, 0xb0, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00 }
[2020-12-28 14:18:43.970] 
[2020-12-28 14:18:43.970] Area:
[2020-12-28 14:18:43.970]   Desktop = 1024px x 768px
[2020-12-28 14:18:43.970]   Screen Map = 1024px x 768px @ X+0px, Y+0px
[2020-12-28 14:18:43.970]   Tablet =  66.67mm x 50.00mm @ Min(40.00mm, 25.00mm) Max(106.67mm, 75.00mm)
[2020-12-28 14:18:43.970]   Rotation matrix = [1.000000,-0.000000,0.000000,1.000000]
[2020-12-28 14:18:43.970] 
[2020-12-28 14:18:43.970] >> Start
[2020-12-28 14:18:43.970] [ERROR] Tablet init failed!
[2020-12-28 14:18:43.970] [ERROR] Possible fixes:
[2020-12-28 14:18:43.970] [ERROR] 1) Uninstall other tablet drivers.
[2020-12-28 14:18:43.970] [ERROR] 2) Stop other tablet driver services.
Driver stopped!
```

**Comment by AWandererInInternet** [comment]
Update as of this time: After reinstalling Windows 10 with my files and data still intact, the Devcon.exe failed and the No UAC prompt is gone, so it must be a Windows Installation problem since I recently upgraded from 7 to 10, upgrade seems probably the conflict as it replaces files and stuff like that.

**Comment by AWandererInInternet** [comment]
**Update as of this time**: After further investigation, about the *Devcon failed. issue*, it turns out to be a permissions problem, since I granted myself permissions to view system32 and the config folder inside system32 when I was doing something, I removed myself from the permissions list and everything works as it should now.

How to reproduce devcon.exe failed:
Grant yourself admin permissions to **view** the system32 folder and **config** folder.
Open the install or remove drivers hawku .bat files.

**Comment by AWandererInInternet** [comment]
## devcon.exe failed problem not involving permissions
From what I see, their problem is not a folder permissions problem.
And the majority, their OS is Windows 8.
It goes like this:
```Device node created
Updating drivers for xxx
devcon.exe failed
```


This is entirely different from my issue shown above.

**Comment by Xayanide** [comment]
## December 16, 2018 - Default Tablet Configuration of G640s Unchanged in TabletDriverV0.2.3
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00
```

## February 13, 2021 - Found a Solution for Tablet Init failed

Sources, Credits, References: 

Issue Number 
#990 
Method 1
https://github.com/hawku/TabletDriver/issues/990#issuecomment-778399795
Method 2, Method 3 
https://github.com/hawku/TabletDriver/issues/990#issuecomment-778567638

## Method 1

Find ```XP-Pen G640s``` in ```TabletDriverV0.2.3\config\tablet.cfg```
Change InitReport to 
```InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00```
Save changes and restart driver.

Method 1 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00
```

## Method 2
If that method did not help you, in my case, it didn't, here is another method that did solved my issue, hopefully it works for you as well.

Change ReportLength to
```ReportLength 12```

Replace InitReport with 
```InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00```

Method 2 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 12
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
```

## Method 3
However, if it still didn't work for you and still gave you the error, try these below.

```ReportLength 10``` 
```InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x0```

Method 3 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x0
```

## Post Scriptum

You can copy paste the Config code blocks and paste it into your tablet.cfg file, find G640s section and paste it there.

Alternatively just change each ```ReportLength``` and ```InitReport``` since those two are the only ones needed changes.

I made a ZIP file, inside are folders with ```tablet.cfg``` files.
Retaining every configuration of tablets,
But only changed the G640s section.

Attachment:
[G640s Tablet Configs.zip](https://github.com/hawku/TabletDriver/files/6132257/G640s.Tablet.Configs.zip)

It has folders namely ```Method 1```, ```Method 2```, ```Method 3``` with ```tablet.cfg``` files. 
With different configurations being made according to the methods above, this is just an alternative if you are lazy copy pasting texts and just want to copy paste and replace the config folder and the files inside altogether.

Steps:
1 Open ```G640s.Tablet.Configs.zip``` or extract it & move to Step 3
2 Choose and Open any of the folders namely ```Method 1```, ```Method 2```, ```Method 3```
3 Copy or Move the ```config``` folder.
4 Paste it to your ```TabletDriverV0.2.3``` folder.
5 If it asks you to Replace the folder or ```tablet.cfg```
6 Replace it.
7 Run ```TabletDriverGUI.exe```
If the Error appears, try the other Method folders and do the steps again.

**Comment by SpicyDice** [comment]
Method 2 Solved my Issue.
You have my thanks for gathering this information and putting it altogether.

Thanks also for providing the sources and crediting them.

**Comment by SpicyDice** [comment]
You have my thanks for gathering these Information, putting them altogether, providing and crediting the sources.

**Comment by SpicyDice** [comment]
You have my thanks for providing the sources, gathering the information and putting them altogether.

**Comment by SpicyDice** [comment]
Method 2 solved my issue completely.

You have my thanks for providing the sources, gathering the information and putting them altogether.

**Comment by Xayanide** [comment]
## December 16, 2018 - Default Tablet Configuration of G640s Unchanged in TabletDriverV0.2.3
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00
```

## January 12, 2021 - Found a Solution for Tablet Init failed

Sources, Credits, References: 

Issue Numbers 
#941 
#990 

Method 1
https://github.com/hawku/TabletDriver/issues/990#issuecomment-778399795
Method 2, Method 3 
https://github.com/hawku/TabletDriver/issues/941#issuecomment-758519839
https://github.com/hawku/TabletDriver/issues/990#issuecomment-778567638

## Method 1

Find ```XP-Pen G640s``` in ```TabletDriverV0.2.3\config\tablet.cfg```
Change InitReport to 
```InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00```
Save changes and restart driver.

Method 1 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00
```

## Method 2
If that method did not help you, in my case, it didn't, here is another method that did solved my issue, hopefully it works for you as well.

Change ReportLength to
```ReportLength 12```

Replace InitReport with 
```InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00```

Method 2 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 12
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
```

## Method 3
However, if it still didn't work for you and still gave you the error, try these below.

```ReportLength 10``` 
```InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x0```

Method 3 Config:
```
#
# XP-Pen G640s
#
HIDTablet 0x28BD 0x0906 0xFF0A 0x0001
Name "XP-Pen G640s"
ReportId 0x02
ReportLength 10
DetectMask 0x80
MaxX 32000
MaxY 20000
MaxPressure 8191
Width 160.0
Height 100.0
InitReport 0x02 0xB0 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x0
```

## Post Scriptum

You can copy paste the Config code blocks and paste it into your tablet.cfg file, find G640s section and paste it there.

Alternatively just change each ```ReportLength``` and ```InitReport``` since those two are the only ones needed changes.

I made a ZIP file, inside are folders with ```tablet.cfg``` files.
Retaining every configuration of tablets,
But only changed the G640s section.

Attachment:
[G640s.Tablet.Configs.zip](https://github.com/hawku/TabletDriver/files/6132257/G640s.Tablet.Configs.zip)

It has folders namely ```Method 1```, ```Method 2```, ```Method 3``` with ```tablet.cfg``` files. 
With different configurations being made according to the methods above, this is just an alternative if you are lazy copy pasting texts and just want to copy paste and replace the config folder and the files inside altogether.

Steps:
1 Open ```G640s.Tablet.Configs.zip``` or extract it & move to Step 3
2 Choose and Open any of the folders namely ```Method 1```, ```Method 2```, ```Method 3```
3 Copy or Move the ```config``` folder.
4 Paste it to your ```TabletDriverV0.2.3``` folder.
5 If it asks you to Replace the folder or ```tablet.cfg```
6 Replace it.
7 Run ```TabletDriverGUI.exe```
If the Error appears, try the other Method folders and do the steps again.

**Comment by SpicyDice** [comment]
Method 2 solved my issue completely.

You have my thanks for crediting the sources, gathering all the information and putting them altogether.
