### ISSUE TITLE
Pressure Sensitivity?

### ISSUE THREAD

**Issue by syrno** [hawku/TabletDriver#95]
Is there a way to have pressure sensitivity and still use this driver otherwise?

## Hardware/software information
Windows Version: 10

Tablet Driver version: Newest

Tablet model: 490

**Comment by hawku** [comment]
The Windows Ink mode supports pen pressure.

**Comment by syrno** [comment]
Doesn't work for me.

Care to explain in more detail?

**Comment by hawku** [comment]
@syrno Windows Ink is the official pen support for Windows.
https://www.microsoft.com/en-us/windows/windows-ink

If the drawing application supports Windows Ink, then the pressure sensitivity in Windows Ink mode should work with that app.

The driver doesn't support the old WinTab interface which is used by GIMP and several other digital art applications.
