### ISSUE TITLE
Linux support request

### ISSUE THREAD

**Issue by Maritsu** [hawku/TabletDriver#994]
So I've tried the official XP-Pen drivers but they're unusable and I remembered these drivers exist. I'm not a Windows user though and I think these drivers are the only ones that would support my tablet but I can see there's no Linux version. So I'd request Linux support for these drivers.

## Hardware/software information
~~Windows Version:~~
**Linux Version:** Ubuntu 20.04 LTS

**Tablet Driver version:** None, as there is no Linux support yet

**Tablet model:** XP-Pen Star G430S

**Comment by tilda** [comment]
OpenTabletDriver seems to fully support your tablet and is cross-platform. https://github.com/InfinityGhost/OpenTabletDriver

**Comment by Maritsu** [comment]
Alright, thanks for help
